//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.CollegeCreditEarnedBeforeHighSchoolGraduationCodeType;
import org.pesc.core.coremain.v1_14.StudentLevelType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * <p>Java class for AcademicRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="School" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}SchoolType" minOccurs="0"/>
 *         &lt;element name="FirstDateAttended" type="{urn:org:pesc:core:CoreMain:v1.14.0}FirstDateAttendedType" minOccurs="0"/>
 *         &lt;element name="LastDateAttended" type="{urn:org:pesc:core:CoreMain:v1.14.0}LastDateAttendedType" minOccurs="0"/>
 *         &lt;element name="SchoolAssignedPersonID" type="{urn:org:pesc:core:CoreMain:v1.14.0}SchoolAssignedPersonIDType" minOccurs="0"/>
 *         &lt;element name="StudentLevel" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentLevelType" minOccurs="0"/>
 *         &lt;element name="AcademicAward" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicAwardType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AcademicSummary" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicSummaryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AcademicSession" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicSessionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Course" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}CourseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionalStudentAchievements" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AdditionalStudentAchievementsType" minOccurs="0"/>
 *         &lt;element name="HighSchoolSubjectArea" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}HighSchoolSubjectAreaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ClassRank" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ClassRankType" minOccurs="0"/>
 *         &lt;element name="AcademicProgram" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicProgramType" minOccurs="0"/>
 *         &lt;element name="CollegeCreditEarnedBeforeHighSchoolGraduationCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CollegeCreditEarnedBeforeHighSchoolGraduationCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicRecordType", propOrder = {
    "school",
    "firstDateAttended",
    "lastDateAttended",
    "schoolAssignedPersonID",
    "studentLevel",
    "academicAward",
    "academicSummary",
    "academicSession",
    "course",
    "additionalStudentAchievements",
    "highSchoolSubjectArea",
    "classRank",
    "academicProgram",
    "collegeCreditEarnedBeforeHighSchoolGraduationCode",
    "userDefinedExtensions",
    "noteMessage"
})
public class AcademicRecordType {

    @XmlElement(name = "School")
    protected SchoolType school;
    @XmlElement(name = "FirstDateAttended")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstDateAttended;
    @XmlElement(name = "LastDateAttended")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastDateAttended;
    @XmlElement(name = "SchoolAssignedPersonID")
    protected String schoolAssignedPersonID;
    @XmlElement(name = "StudentLevel")
    protected StudentLevelType studentLevel;
    @XmlElement(name = "AcademicAward")
    protected List<AcademicAwardType> academicAward;
    @XmlElement(name = "AcademicSummary")
    protected List<AcademicSummaryType> academicSummary;
    @XmlElement(name = "AcademicSession")
    protected List<AcademicSessionType> academicSession;
    @XmlElement(name = "Course")
    protected List<CourseType> course;
    @XmlElement(name = "AdditionalStudentAchievements")
    protected AdditionalStudentAchievementsType additionalStudentAchievements;
    @XmlElement(name = "HighSchoolSubjectArea")
    protected List<HighSchoolSubjectAreaType> highSchoolSubjectArea;
    @XmlElement(name = "ClassRank")
    protected ClassRankType classRank;
    @XmlElement(name = "AcademicProgram")
    protected AcademicProgramType academicProgram;
    @XmlElement(name = "CollegeCreditEarnedBeforeHighSchoolGraduationCode")
    @XmlSchemaType(name = "string")
    protected List<CollegeCreditEarnedBeforeHighSchoolGraduationCodeType> collegeCreditEarnedBeforeHighSchoolGraduationCode;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolType }
     *     
     */
    public SchoolType getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolType }
     *     
     */
    public void setSchool(SchoolType value) {
        this.school = value;
    }

    /**
     * Gets the value of the firstDateAttended property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstDateAttended() {
        return firstDateAttended;
    }

    /**
     * Sets the value of the firstDateAttended property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstDateAttended(XMLGregorianCalendar value) {
        this.firstDateAttended = value;
    }

    /**
     * Gets the value of the lastDateAttended property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDateAttended() {
        return lastDateAttended;
    }

    /**
     * Sets the value of the lastDateAttended property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDateAttended(XMLGregorianCalendar value) {
        this.lastDateAttended = value;
    }

    /**
     * Gets the value of the schoolAssignedPersonID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolAssignedPersonID() {
        return schoolAssignedPersonID;
    }

    /**
     * Sets the value of the schoolAssignedPersonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolAssignedPersonID(String value) {
        this.schoolAssignedPersonID = value;
    }

    /**
     * Gets the value of the studentLevel property.
     * 
     * @return
     *     possible object is
     *     {@link StudentLevelType }
     *     
     */
    public StudentLevelType getStudentLevel() {
        return studentLevel;
    }

    /**
     * Sets the value of the studentLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentLevelType }
     *     
     */
    public void setStudentLevel(StudentLevelType value) {
        this.studentLevel = value;
    }

    /**
     * Gets the value of the academicAward property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicAward property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicAward().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicAwardType }
     * 
     * 
     */
    public List<AcademicAwardType> getAcademicAward() {
        if (academicAward == null) {
            academicAward = new ArrayList<AcademicAwardType>();
        }
        return this.academicAward;
    }

    /**
     * Gets the value of the academicSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicSummaryType }
     * 
     * 
     */
    public List<AcademicSummaryType> getAcademicSummary() {
        if (academicSummary == null) {
            academicSummary = new ArrayList<AcademicSummaryType>();
        }
        return this.academicSummary;
    }

    /**
     * Gets the value of the academicSession property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the academicSession property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcademicSession().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicSessionType }
     * 
     * 
     */
    public List<AcademicSessionType> getAcademicSession() {
        if (academicSession == null) {
            academicSession = new ArrayList<AcademicSessionType>();
        }
        return this.academicSession;
    }

    /**
     * Gets the value of the course property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the course property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourseType }
     * 
     * 
     */
    public List<CourseType> getCourse() {
        if (course == null) {
            course = new ArrayList<CourseType>();
        }
        return this.course;
    }

    /**
     * Gets the value of the additionalStudentAchievements property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStudentAchievementsType }
     *     
     */
    public AdditionalStudentAchievementsType getAdditionalStudentAchievements() {
        return additionalStudentAchievements;
    }

    /**
     * Sets the value of the additionalStudentAchievements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStudentAchievementsType }
     *     
     */
    public void setAdditionalStudentAchievements(AdditionalStudentAchievementsType value) {
        this.additionalStudentAchievements = value;
    }

    /**
     * Gets the value of the highSchoolSubjectArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highSchoolSubjectArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighSchoolSubjectArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HighSchoolSubjectAreaType }
     * 
     * 
     */
    public List<HighSchoolSubjectAreaType> getHighSchoolSubjectArea() {
        if (highSchoolSubjectArea == null) {
            highSchoolSubjectArea = new ArrayList<HighSchoolSubjectAreaType>();
        }
        return this.highSchoolSubjectArea;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link ClassRankType }
     *     
     */
    public ClassRankType getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassRankType }
     *     
     */
    public void setClassRank(ClassRankType value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the academicProgram property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicProgramType }
     *     
     */
    public AcademicProgramType getAcademicProgram() {
        return academicProgram;
    }

    /**
     * Sets the value of the academicProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicProgramType }
     *     
     */
    public void setAcademicProgram(AcademicProgramType value) {
        this.academicProgram = value;
    }

    /**
     * Gets the value of the collegeCreditEarnedBeforeHighSchoolGraduationCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collegeCreditEarnedBeforeHighSchoolGraduationCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollegeCreditEarnedBeforeHighSchoolGraduationCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CollegeCreditEarnedBeforeHighSchoolGraduationCodeType }
     * 
     * 
     */
    public List<CollegeCreditEarnedBeforeHighSchoolGraduationCodeType> getCollegeCreditEarnedBeforeHighSchoolGraduationCode() {
        if (collegeCreditEarnedBeforeHighSchoolGraduationCode == null) {
            collegeCreditEarnedBeforeHighSchoolGraduationCode = new ArrayList<CollegeCreditEarnedBeforeHighSchoolGraduationCodeType>();
        }
        return this.collegeCreditEarnedBeforeHighSchoolGraduationCode;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
