//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.AcademicHonorsType;
import org.pesc.core.coremain.v1_14.AcademicSummaryTypeType;
import org.pesc.core.coremain.v1_14.CourseCreditLevelType;
import org.pesc.core.coremain.v1_14.DelinquenciesType;
import org.pesc.core.coremain.v1_14.GPAType;


/**
 * <p>Java class for AcademicSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcademicSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicSummaryCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicSummaryTypeType" minOccurs="0"/>
 *         &lt;element name="AcademicSummaryLevel" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCreditLevelType" minOccurs="0"/>
 *         &lt;element name="GPA" type="{urn:org:pesc:core:CoreMain:v1.14.0}GPAType" minOccurs="0"/>
 *         &lt;element name="AcademicHonors" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicHonorsType" minOccurs="0"/>
 *         &lt;element name="ClassRank" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassRankType" minOccurs="0"/>
 *         &lt;element name="ClassSize" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassSizeType" minOccurs="0"/>
 *         &lt;element name="AcademicProgram" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicProgramType" minOccurs="0"/>
 *         &lt;element name="Delinquencies" type="{urn:org:pesc:core:CoreMain:v1.14.0}DelinquenciesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExitDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}ExitDateType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcademicSummaryType", propOrder = {
    "academicSummaryCode",
    "academicSummaryLevel",
    "gpa",
    "academicHonors",
    "classRank",
    "classSize",
    "academicProgram",
    "delinquencies",
    "exitDate",
    "noteMessage"
})
public class AcademicSummaryType {

    @XmlElement(name = "AcademicSummaryCode")
    @XmlSchemaType(name = "string")
    protected AcademicSummaryTypeType academicSummaryCode;
    @XmlElement(name = "AcademicSummaryLevel")
    @XmlSchemaType(name = "string")
    protected CourseCreditLevelType academicSummaryLevel;
    @XmlElement(name = "GPA")
    protected GPAType gpa;
    @XmlElement(name = "AcademicHonors")
    protected AcademicHonorsType academicHonors;
    @XmlElement(name = "ClassRank")
    @XmlSchemaType(name = "integer")
    protected Integer classRank;
    @XmlElement(name = "ClassSize")
    @XmlSchemaType(name = "integer")
    protected Integer classSize;
    @XmlElement(name = "AcademicProgram")
    protected AcademicProgramType academicProgram;
    @XmlElement(name = "Delinquencies")
    @XmlSchemaType(name = "string")
    protected List<DelinquenciesType> delinquencies;
    @XmlElement(name = "ExitDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exitDate;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the academicSummaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicSummaryTypeType }
     *     
     */
    public AcademicSummaryTypeType getAcademicSummaryCode() {
        return academicSummaryCode;
    }

    /**
     * Sets the value of the academicSummaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicSummaryTypeType }
     *     
     */
    public void setAcademicSummaryCode(AcademicSummaryTypeType value) {
        this.academicSummaryCode = value;
    }

    /**
     * Gets the value of the academicSummaryLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CourseCreditLevelType }
     *     
     */
    public CourseCreditLevelType getAcademicSummaryLevel() {
        return academicSummaryLevel;
    }

    /**
     * Sets the value of the academicSummaryLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseCreditLevelType }
     *     
     */
    public void setAcademicSummaryLevel(CourseCreditLevelType value) {
        this.academicSummaryLevel = value;
    }

    /**
     * Gets the value of the gpa property.
     * 
     * @return
     *     possible object is
     *     {@link GPAType }
     *     
     */
    public GPAType getGPA() {
        return gpa;
    }

    /**
     * Sets the value of the gpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPAType }
     *     
     */
    public void setGPA(GPAType value) {
        this.gpa = value;
    }

    /**
     * Gets the value of the academicHonors property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicHonorsType }
     *     
     */
    public AcademicHonorsType getAcademicHonors() {
        return academicHonors;
    }

    /**
     * Sets the value of the academicHonors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicHonorsType }
     *     
     */
    public void setAcademicHonors(AcademicHonorsType value) {
        this.academicHonors = value;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassRank(Integer value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the classSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassSize() {
        return classSize;
    }

    /**
     * Sets the value of the classSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassSize(Integer value) {
        this.classSize = value;
    }

    /**
     * Gets the value of the academicProgram property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicProgramType }
     *     
     */
    public AcademicProgramType getAcademicProgram() {
        return academicProgram;
    }

    /**
     * Sets the value of the academicProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicProgramType }
     *     
     */
    public void setAcademicProgram(AcademicProgramType value) {
        this.academicProgram = value;
    }

    /**
     * Gets the value of the delinquencies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delinquencies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelinquencies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DelinquenciesType }
     * 
     * 
     */
    public List<DelinquenciesType> getDelinquencies() {
        if (delinquencies == null) {
            delinquencies = new ArrayList<DelinquenciesType>();
        }
        return this.delinquencies;
    }

    /**
     * Gets the value of the exitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExitDate() {
        return exitDate;
    }

    /**
     * Sets the value of the exitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExitDate(XMLGregorianCalendar value) {
        this.exitDate = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
