//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ActiveDutyMilitaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActiveDutyMilitaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MilitaryDutyBranch" type="{urn:org:pesc:core:CoreMain:v1.14.0}MilitaryDutyBranchType" minOccurs="0"/>
 *         &lt;element name="MilitaryDutyLocation" type="{urn:org:pesc:core:CoreMain:v1.14.0}MilitaryDutyLocationType" minOccurs="0"/>
 *         &lt;element name="MilitaryDutyBeginDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}MilitaryDutyBeginDateType" minOccurs="0"/>
 *         &lt;element name="MilitaryDutyEndDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}MilitaryDutyEndDateType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActiveDutyMilitaryType", propOrder = {
    "militaryDutyBranch",
    "militaryDutyLocation",
    "militaryDutyBeginDate",
    "militaryDutyEndDate",
    "noteMessage"
})
public class ActiveDutyMilitaryType {

    @XmlElement(name = "MilitaryDutyBranch")
    protected String militaryDutyBranch;
    @XmlElement(name = "MilitaryDutyLocation")
    protected String militaryDutyLocation;
    @XmlElement(name = "MilitaryDutyBeginDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar militaryDutyBeginDate;
    @XmlElement(name = "MilitaryDutyEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar militaryDutyEndDate;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the militaryDutyBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMilitaryDutyBranch() {
        return militaryDutyBranch;
    }

    /**
     * Sets the value of the militaryDutyBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMilitaryDutyBranch(String value) {
        this.militaryDutyBranch = value;
    }

    /**
     * Gets the value of the militaryDutyLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMilitaryDutyLocation() {
        return militaryDutyLocation;
    }

    /**
     * Sets the value of the militaryDutyLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMilitaryDutyLocation(String value) {
        this.militaryDutyLocation = value;
    }

    /**
     * Gets the value of the militaryDutyBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMilitaryDutyBeginDate() {
        return militaryDutyBeginDate;
    }

    /**
     * Sets the value of the militaryDutyBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMilitaryDutyBeginDate(XMLGregorianCalendar value) {
        this.militaryDutyBeginDate = value;
    }

    /**
     * Gets the value of the militaryDutyEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMilitaryDutyEndDate() {
        return militaryDutyEndDate;
    }

    /**
     * Sets the value of the militaryDutyEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMilitaryDutyEndDate(XMLGregorianCalendar value) {
        this.militaryDutyEndDate = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
