//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.CreditCardIssuerCodeType;
import org.pesc.core.coremain.v1_14.FeeWaiverBasisCodeType;
import org.pesc.core.coremain.v1_14.PaymentMethodCodeType;


/**
 * <p>Java class for ApplicationFeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationFeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationFeeAmount" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationFeeAmountType" minOccurs="0"/>
 *         &lt;element name="PaymentMethodCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}PaymentMethodCodeType" minOccurs="0"/>
 *         &lt;element name="FeeWaiverBasisCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}FeeWaiverBasisCodeType" minOccurs="0"/>
 *         &lt;element name="CardIssuerCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CreditCardIssuerCodeType" minOccurs="0"/>
 *         &lt;element name="CardNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}CreditCardNumberType" minOccurs="0"/>
 *         &lt;element name="CardNumberLast4" type="{urn:org:pesc:core:CoreMain:v1.14.0}CreditCardNumberLast4Type" minOccurs="0"/>
 *         &lt;element name="CardExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}CreditCardExpirationDateType" minOccurs="0"/>
 *         &lt;element name="NameOnCard" type="{urn:org:pesc:core:CoreMain:v1.14.0}NameOnCardType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationFeeType", propOrder = {
    "applicationFeeAmount",
    "paymentMethodCode",
    "feeWaiverBasisCode",
    "cardIssuerCode",
    "cardNumber",
    "cardNumberLast4",
    "cardExpirationDate",
    "nameOnCard",
    "noteMessage"
})
public class ApplicationFeeType {

    @XmlElement(name = "ApplicationFeeAmount")
    protected BigDecimal applicationFeeAmount;
    @XmlElement(name = "PaymentMethodCode")
    @XmlSchemaType(name = "string")
    protected PaymentMethodCodeType paymentMethodCode;
    @XmlElement(name = "FeeWaiverBasisCode")
    @XmlSchemaType(name = "string")
    protected FeeWaiverBasisCodeType feeWaiverBasisCode;
    @XmlElement(name = "CardIssuerCode")
    @XmlSchemaType(name = "string")
    protected CreditCardIssuerCodeType cardIssuerCode;
    @XmlElement(name = "CardNumber")
    protected String cardNumber;
    @XmlElement(name = "CardNumberLast4")
    protected String cardNumberLast4;
    @XmlElement(name = "CardExpirationDate")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar cardExpirationDate;
    @XmlElement(name = "NameOnCard")
    protected String nameOnCard;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the applicationFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApplicationFeeAmount() {
        return applicationFeeAmount;
    }

    /**
     * Sets the value of the applicationFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApplicationFeeAmount(BigDecimal value) {
        this.applicationFeeAmount = value;
    }

    /**
     * Gets the value of the paymentMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodCodeType }
     *     
     */
    public PaymentMethodCodeType getPaymentMethodCode() {
        return paymentMethodCode;
    }

    /**
     * Sets the value of the paymentMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodCodeType }
     *     
     */
    public void setPaymentMethodCode(PaymentMethodCodeType value) {
        this.paymentMethodCode = value;
    }

    /**
     * Gets the value of the feeWaiverBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link FeeWaiverBasisCodeType }
     *     
     */
    public FeeWaiverBasisCodeType getFeeWaiverBasisCode() {
        return feeWaiverBasisCode;
    }

    /**
     * Sets the value of the feeWaiverBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeWaiverBasisCodeType }
     *     
     */
    public void setFeeWaiverBasisCode(FeeWaiverBasisCodeType value) {
        this.feeWaiverBasisCode = value;
    }

    /**
     * Gets the value of the cardIssuerCode property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardIssuerCodeType }
     *     
     */
    public CreditCardIssuerCodeType getCardIssuerCode() {
        return cardIssuerCode;
    }

    /**
     * Sets the value of the cardIssuerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardIssuerCodeType }
     *     
     */
    public void setCardIssuerCode(CreditCardIssuerCodeType value) {
        this.cardIssuerCode = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the cardNumberLast4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumberLast4() {
        return cardNumberLast4;
    }

    /**
     * Sets the value of the cardNumberLast4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumberLast4(String value) {
        this.cardNumberLast4 = value;
    }

    /**
     * Gets the value of the cardExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardExpirationDate() {
        return cardExpirationDate;
    }

    /**
     * Sets the value of the cardExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardExpirationDate(XMLGregorianCalendar value) {
        this.cardExpirationDate = value;
    }

    /**
     * Gets the value of the nameOnCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOnCard() {
        return nameOnCard;
    }

    /**
     * Sets the value of the nameOnCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOnCard(String value) {
        this.nameOnCard = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
