//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.AcademicSessionDetailType;
import org.pesc.core.coremain.v1_14.EarlyIndicatorCodeType;


/**
 * <p>Java class for ApplicationDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationSession" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicSessionDetailType"/>
 *         &lt;element name="ApplicationDegreeProgram" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicProgramType" maxOccurs="unbounded"/>
 *         &lt;element name="ApplicationOrganization" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ApplicationOrganizationType" minOccurs="0"/>
 *         &lt;element name="CampusName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CampusNameType" minOccurs="0"/>
 *         &lt;element name="EarlyIndicatorCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}EarlyIndicatorCodeType" minOccurs="0"/>
 *         &lt;element name="ApplicationPriority" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationPriorityType" minOccurs="0"/>
 *         &lt;element name="ApplicationWithdrawalIndicator" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationWithdrawalIndicatorType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationDetailType", propOrder = {
    "applicationSession",
    "applicationDegreeProgram",
    "applicationOrganization",
    "campusName",
    "earlyIndicatorCode",
    "applicationPriority",
    "applicationWithdrawalIndicator",
    "noteMessage"
})
public class ApplicationDetailType {

    @XmlElement(name = "ApplicationSession", required = true)
    protected AcademicSessionDetailType applicationSession;
    @XmlElement(name = "ApplicationDegreeProgram", required = true)
    protected List<AcademicProgramType> applicationDegreeProgram;
    @XmlElement(name = "ApplicationOrganization")
    protected ApplicationOrganizationType applicationOrganization;
    @XmlElement(name = "CampusName")
    protected String campusName;
    @XmlElement(name = "EarlyIndicatorCode")
    @XmlSchemaType(name = "string")
    protected EarlyIndicatorCodeType earlyIndicatorCode;
    @XmlElement(name = "ApplicationPriority")
    protected Integer applicationPriority;
    @XmlElement(name = "ApplicationWithdrawalIndicator")
    protected Boolean applicationWithdrawalIndicator;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the applicationSession property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicSessionDetailType }
     *     
     */
    public AcademicSessionDetailType getApplicationSession() {
        return applicationSession;
    }

    /**
     * Sets the value of the applicationSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicSessionDetailType }
     *     
     */
    public void setApplicationSession(AcademicSessionDetailType value) {
        this.applicationSession = value;
    }

    /**
     * Gets the value of the applicationDegreeProgram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationDegreeProgram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationDegreeProgram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicProgramType }
     * 
     * 
     */
    public List<AcademicProgramType> getApplicationDegreeProgram() {
        if (applicationDegreeProgram == null) {
            applicationDegreeProgram = new ArrayList<AcademicProgramType>();
        }
        return this.applicationDegreeProgram;
    }

    /**
     * Gets the value of the applicationOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationOrganizationType }
     *     
     */
    public ApplicationOrganizationType getApplicationOrganization() {
        return applicationOrganization;
    }

    /**
     * Sets the value of the applicationOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationOrganizationType }
     *     
     */
    public void setApplicationOrganization(ApplicationOrganizationType value) {
        this.applicationOrganization = value;
    }

    /**
     * Gets the value of the campusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampusName() {
        return campusName;
    }

    /**
     * Sets the value of the campusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampusName(String value) {
        this.campusName = value;
    }

    /**
     * Gets the value of the earlyIndicatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link EarlyIndicatorCodeType }
     *     
     */
    public EarlyIndicatorCodeType getEarlyIndicatorCode() {
        return earlyIndicatorCode;
    }

    /**
     * Sets the value of the earlyIndicatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarlyIndicatorCodeType }
     *     
     */
    public void setEarlyIndicatorCode(EarlyIndicatorCodeType value) {
        this.earlyIndicatorCode = value;
    }

    /**
     * Gets the value of the applicationPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getApplicationPriority() {
        return applicationPriority;
    }

    /**
     * Sets the value of the applicationPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setApplicationPriority(Integer value) {
        this.applicationPriority = value;
    }

    /**
     * Gets the value of the applicationWithdrawalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplicationWithdrawalIndicator() {
        return applicationWithdrawalIndicator;
    }

    /**
     * Sets the value of the applicationWithdrawalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplicationWithdrawalIndicator(Boolean value) {
        this.applicationWithdrawalIndicator = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
