//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.AcademicAwardEarnedPriorToAdmissionCodeType;
import org.pesc.core.coremain.v1_14.ApplicationProcessingGroupCodeType;
import org.pesc.core.coremain.v1_14.ApplicationSourceType;
import org.pesc.core.coremain.v1_14.StudentReleaseCodeType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * <p>Java class for ApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationDetail" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ApplicationDetailType" maxOccurs="unbounded"/>
 *         &lt;element name="ApplicationStatement" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RecommendationReference" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}RecommendationReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApplicationQuestion" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AdmissionsApplicationQuestionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AcademicAwardEarnedPriorToAdmissionCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicAwardEarnedPriorToAdmissionCodeType" minOccurs="0"/>
 *         &lt;element name="AdditionalStudentAchievements" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AdditionalStudentAchievementsType" minOccurs="0"/>
 *         &lt;element name="ApplicationProcessingGroupCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationProcessingGroupCodeType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="StudentReleaseCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentReleaseCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlanToApplyFor" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}PlanToApplyForType" minOccurs="0"/>
 *         &lt;element name="DecisionToApply" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}DecisionToApplyType" minOccurs="0"/>
 *         &lt;element name="HousingInformation" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}HousingInformationType" minOccurs="0"/>
 *         &lt;element name="InformationRequested" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}InfoRequestedType" minOccurs="0"/>
 *         &lt;element name="ApplicationFee" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ApplicationFeeType" minOccurs="0"/>
 *         &lt;element name="ActivityParticipationRequest" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ActivityParticipationRequestType" minOccurs="0"/>
 *         &lt;element name="PreviousApplication" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}PreviousApplicationType" minOccurs="0"/>
 *         &lt;element name="OtherCollegeApplication" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}OtherCollegeApplicationType" minOccurs="0"/>
 *         &lt;element name="Sponsor" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}SponsorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApplicationID" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationIDType" minOccurs="0"/>
 *         &lt;element name="ApplicationSource" type="{urn:org:pesc:core:CoreMain:v1.14.0}ApplicationSourceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationType", propOrder = {
    "applicationDetail",
    "applicationStatement",
    "recommendationReference",
    "applicationQuestion",
    "academicAwardEarnedPriorToAdmissionCode",
    "additionalStudentAchievements",
    "applicationProcessingGroupCode",
    "studentReleaseCode",
    "planToApplyFor",
    "decisionToApply",
    "housingInformation",
    "informationRequested",
    "applicationFee",
    "activityParticipationRequest",
    "previousApplication",
    "otherCollegeApplication",
    "sponsor",
    "userDefinedExtensions",
    "noteMessage",
    "applicationID",
    "applicationSource"
})
public class ApplicationType {

    @XmlElement(name = "ApplicationDetail", required = true)
    protected List<ApplicationDetailType> applicationDetail;
    @XmlElement(name = "ApplicationStatement")
    protected List<Object> applicationStatement;
    @XmlElement(name = "RecommendationReference")
    protected List<RecommendationReferenceType> recommendationReference;
    @XmlElement(name = "ApplicationQuestion")
    protected List<AdmissionsApplicationQuestionType> applicationQuestion;
    @XmlElement(name = "AcademicAwardEarnedPriorToAdmissionCode")
    @XmlSchemaType(name = "string")
    protected AcademicAwardEarnedPriorToAdmissionCodeType academicAwardEarnedPriorToAdmissionCode;
    @XmlElement(name = "AdditionalStudentAchievements")
    protected AdditionalStudentAchievementsType additionalStudentAchievements;
    @XmlElement(name = "ApplicationProcessingGroupCode")
    @XmlSchemaType(name = "string")
    protected List<ApplicationProcessingGroupCodeType> applicationProcessingGroupCode;
    @XmlElement(name = "StudentReleaseCode")
    @XmlSchemaType(name = "string")
    protected List<StudentReleaseCodeType> studentReleaseCode;
    @XmlElement(name = "PlanToApplyFor")
    protected PlanToApplyForType planToApplyFor;
    @XmlElement(name = "DecisionToApply")
    protected DecisionToApplyType decisionToApply;
    @XmlElement(name = "HousingInformation")
    protected HousingInformationType housingInformation;
    @XmlElement(name = "InformationRequested")
    protected InfoRequestedType informationRequested;
    @XmlElement(name = "ApplicationFee")
    protected ApplicationFeeType applicationFee;
    @XmlElement(name = "ActivityParticipationRequest")
    protected ActivityParticipationRequestType activityParticipationRequest;
    @XmlElement(name = "PreviousApplication")
    protected PreviousApplicationType previousApplication;
    @XmlElement(name = "OtherCollegeApplication")
    protected OtherCollegeApplicationType otherCollegeApplication;
    @XmlElement(name = "Sponsor")
    protected List<SponsorType> sponsor;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;
    @XmlElement(name = "ApplicationID")
    protected String applicationID;
    @XmlElement(name = "ApplicationSource")
    @XmlSchemaType(name = "string")
    protected ApplicationSourceType applicationSource;

    /**
     * Gets the value of the applicationDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationDetailType }
     * 
     * 
     */
    public List<ApplicationDetailType> getApplicationDetail() {
        if (applicationDetail == null) {
            applicationDetail = new ArrayList<ApplicationDetailType>();
        }
        return this.applicationDetail;
    }

    /**
     * Gets the value of the applicationStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getApplicationStatement() {
        if (applicationStatement == null) {
            applicationStatement = new ArrayList<Object>();
        }
        return this.applicationStatement;
    }

    /**
     * Gets the value of the recommendationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recommendationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecommendationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecommendationReferenceType }
     * 
     * 
     */
    public List<RecommendationReferenceType> getRecommendationReference() {
        if (recommendationReference == null) {
            recommendationReference = new ArrayList<RecommendationReferenceType>();
        }
        return this.recommendationReference;
    }

    /**
     * Gets the value of the applicationQuestion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationQuestion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationQuestion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdmissionsApplicationQuestionType }
     * 
     * 
     */
    public List<AdmissionsApplicationQuestionType> getApplicationQuestion() {
        if (applicationQuestion == null) {
            applicationQuestion = new ArrayList<AdmissionsApplicationQuestionType>();
        }
        return this.applicationQuestion;
    }

    /**
     * Gets the value of the academicAwardEarnedPriorToAdmissionCode property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicAwardEarnedPriorToAdmissionCodeType }
     *     
     */
    public AcademicAwardEarnedPriorToAdmissionCodeType getAcademicAwardEarnedPriorToAdmissionCode() {
        return academicAwardEarnedPriorToAdmissionCode;
    }

    /**
     * Sets the value of the academicAwardEarnedPriorToAdmissionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicAwardEarnedPriorToAdmissionCodeType }
     *     
     */
    public void setAcademicAwardEarnedPriorToAdmissionCode(AcademicAwardEarnedPriorToAdmissionCodeType value) {
        this.academicAwardEarnedPriorToAdmissionCode = value;
    }

    /**
     * Gets the value of the additionalStudentAchievements property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStudentAchievementsType }
     *     
     */
    public AdditionalStudentAchievementsType getAdditionalStudentAchievements() {
        return additionalStudentAchievements;
    }

    /**
     * Sets the value of the additionalStudentAchievements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStudentAchievementsType }
     *     
     */
    public void setAdditionalStudentAchievements(AdditionalStudentAchievementsType value) {
        this.additionalStudentAchievements = value;
    }

    /**
     * Gets the value of the applicationProcessingGroupCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationProcessingGroupCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationProcessingGroupCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationProcessingGroupCodeType }
     * 
     * 
     */
    public List<ApplicationProcessingGroupCodeType> getApplicationProcessingGroupCode() {
        if (applicationProcessingGroupCode == null) {
            applicationProcessingGroupCode = new ArrayList<ApplicationProcessingGroupCodeType>();
        }
        return this.applicationProcessingGroupCode;
    }

    /**
     * Gets the value of the studentReleaseCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studentReleaseCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudentReleaseCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StudentReleaseCodeType }
     * 
     * 
     */
    public List<StudentReleaseCodeType> getStudentReleaseCode() {
        if (studentReleaseCode == null) {
            studentReleaseCode = new ArrayList<StudentReleaseCodeType>();
        }
        return this.studentReleaseCode;
    }

    /**
     * Gets the value of the planToApplyFor property.
     * 
     * @return
     *     possible object is
     *     {@link PlanToApplyForType }
     *     
     */
    public PlanToApplyForType getPlanToApplyFor() {
        return planToApplyFor;
    }

    /**
     * Sets the value of the planToApplyFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanToApplyForType }
     *     
     */
    public void setPlanToApplyFor(PlanToApplyForType value) {
        this.planToApplyFor = value;
    }

    /**
     * Gets the value of the decisionToApply property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionToApplyType }
     *     
     */
    public DecisionToApplyType getDecisionToApply() {
        return decisionToApply;
    }

    /**
     * Sets the value of the decisionToApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionToApplyType }
     *     
     */
    public void setDecisionToApply(DecisionToApplyType value) {
        this.decisionToApply = value;
    }

    /**
     * Gets the value of the housingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link HousingInformationType }
     *     
     */
    public HousingInformationType getHousingInformation() {
        return housingInformation;
    }

    /**
     * Sets the value of the housingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link HousingInformationType }
     *     
     */
    public void setHousingInformation(HousingInformationType value) {
        this.housingInformation = value;
    }

    /**
     * Gets the value of the informationRequested property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRequestedType }
     *     
     */
    public InfoRequestedType getInformationRequested() {
        return informationRequested;
    }

    /**
     * Sets the value of the informationRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRequestedType }
     *     
     */
    public void setInformationRequested(InfoRequestedType value) {
        this.informationRequested = value;
    }

    /**
     * Gets the value of the applicationFee property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationFeeType }
     *     
     */
    public ApplicationFeeType getApplicationFee() {
        return applicationFee;
    }

    /**
     * Sets the value of the applicationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationFeeType }
     *     
     */
    public void setApplicationFee(ApplicationFeeType value) {
        this.applicationFee = value;
    }

    /**
     * Gets the value of the activityParticipationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityParticipationRequestType }
     *     
     */
    public ActivityParticipationRequestType getActivityParticipationRequest() {
        return activityParticipationRequest;
    }

    /**
     * Sets the value of the activityParticipationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityParticipationRequestType }
     *     
     */
    public void setActivityParticipationRequest(ActivityParticipationRequestType value) {
        this.activityParticipationRequest = value;
    }

    /**
     * Gets the value of the previousApplication property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousApplicationType }
     *     
     */
    public PreviousApplicationType getPreviousApplication() {
        return previousApplication;
    }

    /**
     * Sets the value of the previousApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousApplicationType }
     *     
     */
    public void setPreviousApplication(PreviousApplicationType value) {
        this.previousApplication = value;
    }

    /**
     * Gets the value of the otherCollegeApplication property.
     * 
     * @return
     *     possible object is
     *     {@link OtherCollegeApplicationType }
     *     
     */
    public OtherCollegeApplicationType getOtherCollegeApplication() {
        return otherCollegeApplication;
    }

    /**
     * Sets the value of the otherCollegeApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherCollegeApplicationType }
     *     
     */
    public void setOtherCollegeApplication(OtherCollegeApplicationType value) {
        this.otherCollegeApplication = value;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SponsorType }
     * 
     * 
     */
    public List<SponsorType> getSponsor() {
        if (sponsor == null) {
            sponsor = new ArrayList<SponsorType>();
        }
        return this.sponsor;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

    /**
     * Gets the value of the applicationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationID() {
        return applicationID;
    }

    /**
     * Sets the value of the applicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationID(String value) {
        this.applicationID = value;
    }

    /**
     * Gets the value of the applicationSource property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationSourceType }
     *     
     */
    public ApplicationSourceType getApplicationSource() {
        return applicationSource;
    }

    /**
     * Sets the value of the applicationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationSourceType }
     *     
     */
    public void setApplicationSource(ApplicationSourceType value) {
        this.applicationSource = value;
    }

}
