//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.DisabilityConditionCodeType;
import org.pesc.core.coremain.v1_14.GovernmentMilitaryType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * Student Type
 * 
 * <p>Java class for ApplicantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Person" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ApplicantPersonType"/>
 *         &lt;element name="Family" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}FamilyType" minOccurs="0"/>
 *         &lt;element name="Residency" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ResidencyType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="Application" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ApplicationType" maxOccurs="unbounded"/>
 *         &lt;element name="HealthCondition" type="{urn:org:pesc:core:CoreMain:v1.14.0}BasicHealthType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DisabilityConditionCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DisabilityConditionCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GovernmentMilitary" type="{urn:org:pesc:core:CoreMain:v1.14.0}GovernmentMilitaryType" minOccurs="0"/>
 *         &lt;element name="SelfReportedAcademicRecord" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicRecordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SelfReportedTests" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}TestsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExtraCurricularActivity" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}ExtraCurricularActivityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicantType", propOrder = {
    "person",
    "family",
    "residency",
    "application",
    "healthCondition",
    "disabilityConditionCode",
    "governmentMilitary",
    "selfReportedAcademicRecord",
    "selfReportedTests",
    "extraCurricularActivity",
    "userDefinedExtensions",
    "noteMessage"
})
public class ApplicantType {

    @XmlElement(name = "Person", required = true)
    protected ApplicantPersonType person;
    @XmlElement(name = "Family")
    protected FamilyType family;
    @XmlElement(name = "Residency")
    protected List<ResidencyType> residency;
    @XmlElement(name = "Application", required = true)
    protected List<ApplicationType> application;
    @XmlElement(name = "HealthCondition")
    protected List<String> healthCondition;
    @XmlElement(name = "DisabilityConditionCode")
    @XmlSchemaType(name = "string")
    protected List<DisabilityConditionCodeType> disabilityConditionCode;
    @XmlElement(name = "GovernmentMilitary")
    protected GovernmentMilitaryType governmentMilitary;
    @XmlElement(name = "SelfReportedAcademicRecord")
    protected List<AcademicRecordType> selfReportedAcademicRecord;
    @XmlElement(name = "SelfReportedTests")
    protected List<TestsType> selfReportedTests;
    @XmlElement(name = "ExtraCurricularActivity")
    protected List<ExtraCurricularActivityType> extraCurricularActivity;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantPersonType }
     *     
     */
    public ApplicantPersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantPersonType }
     *     
     */
    public void setPerson(ApplicantPersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyType }
     *     
     */
    public FamilyType getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyType }
     *     
     */
    public void setFamily(FamilyType value) {
        this.family = value;
    }

    /**
     * Gets the value of the residency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the residency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResidency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResidencyType }
     * 
     * 
     */
    public List<ResidencyType> getResidency() {
        if (residency == null) {
            residency = new ArrayList<ResidencyType>();
        }
        return this.residency;
    }

    /**
     * Gets the value of the application property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the application property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationType }
     * 
     * 
     */
    public List<ApplicationType> getApplication() {
        if (application == null) {
            application = new ArrayList<ApplicationType>();
        }
        return this.application;
    }

    /**
     * Gets the value of the healthCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healthCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealthCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHealthCondition() {
        if (healthCondition == null) {
            healthCondition = new ArrayList<String>();
        }
        return this.healthCondition;
    }

    /**
     * Gets the value of the disabilityConditionCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disabilityConditionCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisabilityConditionCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisabilityConditionCodeType }
     * 
     * 
     */
    public List<DisabilityConditionCodeType> getDisabilityConditionCode() {
        if (disabilityConditionCode == null) {
            disabilityConditionCode = new ArrayList<DisabilityConditionCodeType>();
        }
        return this.disabilityConditionCode;
    }

    /**
     * Gets the value of the governmentMilitary property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentMilitaryType }
     *     
     */
    public GovernmentMilitaryType getGovernmentMilitary() {
        return governmentMilitary;
    }

    /**
     * Sets the value of the governmentMilitary property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentMilitaryType }
     *     
     */
    public void setGovernmentMilitary(GovernmentMilitaryType value) {
        this.governmentMilitary = value;
    }

    /**
     * Gets the value of the selfReportedAcademicRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfReportedAcademicRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfReportedAcademicRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcademicRecordType }
     * 
     * 
     */
    public List<AcademicRecordType> getSelfReportedAcademicRecord() {
        if (selfReportedAcademicRecord == null) {
            selfReportedAcademicRecord = new ArrayList<AcademicRecordType>();
        }
        return this.selfReportedAcademicRecord;
    }

    /**
     * Gets the value of the selfReportedTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selfReportedTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelfReportedTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestsType }
     * 
     * 
     */
    public List<TestsType> getSelfReportedTests() {
        if (selfReportedTests == null) {
            selfReportedTests = new ArrayList<TestsType>();
        }
        return this.selfReportedTests;
    }

    /**
     * Gets the value of the extraCurricularActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extraCurricularActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtraCurricularActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraCurricularActivityType }
     * 
     * 
     */
    public List<ExtraCurricularActivityType> getExtraCurricularActivity() {
        if (extraCurricularActivity == null) {
            extraCurricularActivity = new ArrayList<ExtraCurricularActivityType>();
        }
        return this.extraCurricularActivity;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
