//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.AppliedCodeType;


/**
 * <p>Java class for AsyleeRefugeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AsyleeRefugeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AsyleeRefugeeIssueDateType" minOccurs="0"/>
 *         &lt;element name="DocumentExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AsyleeRefugeeExpirationDateType" minOccurs="0"/>
 *         &lt;element name="AppliedDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AsyleeRefugeeAppliedDateType" minOccurs="0"/>
 *         &lt;element name="AppliedCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}AppliedCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AsyleeRefugeeType", propOrder = {
    "issueDate",
    "documentExpirationDate",
    "appliedDate",
    "appliedCode"
})
public class AsyleeRefugeeType {

    @XmlElement(name = "IssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlElement(name = "DocumentExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar documentExpirationDate;
    @XmlElement(name = "AppliedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appliedDate;
    @XmlElement(name = "AppliedCode")
    @XmlSchemaType(name = "string")
    protected AppliedCodeType appliedCode;

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the documentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentExpirationDate() {
        return documentExpirationDate;
    }

    /**
     * Sets the value of the documentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentExpirationDate(XMLGregorianCalendar value) {
        this.documentExpirationDate = value;
    }

    /**
     * Gets the value of the appliedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppliedDate() {
        return appliedDate;
    }

    /**
     * Sets the value of the appliedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppliedDate(XMLGregorianCalendar value) {
        this.appliedDate = value;
    }

    /**
     * Gets the value of the appliedCode property.
     * 
     * @return
     *     possible object is
     *     {@link AppliedCodeType }
     *     
     */
    public AppliedCodeType getAppliedCode() {
        return appliedCode;
    }

    /**
     * Sets the value of the appliedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliedCodeType }
     *     
     */
    public void setAppliedCode(AppliedCodeType value) {
        this.appliedCode = value;
    }

}
