//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CertificateOfEligibilityDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateOfEligibilityDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificateOfEligibilityID" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilityIDType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilityIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilityIssueDateType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilityExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilityExpirationDateType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilityProgramName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilityProgramNameType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilitySchoolName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilitySchoolNameType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilitySchoolCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CertificateOfEligibilitySchoolCodeType" minOccurs="0"/>
 *         &lt;element name="ExchangeVisitorPositionCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}ExchangeVisitorPositionCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateOfEligibilityDetailType", propOrder = {
    "certificateOfEligibilityID",
    "certificateOfEligibilityIssueDate",
    "certificateOfEligibilityExpirationDate",
    "certificateOfEligibilityProgramName",
    "certificateOfEligibilitySchoolName",
    "certificateOfEligibilitySchoolCode",
    "exchangeVisitorPositionCode"
})
public class CertificateOfEligibilityDetailType {

    @XmlElement(name = "CertificateOfEligibilityID")
    protected String certificateOfEligibilityID;
    @XmlElement(name = "CertificateOfEligibilityIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar certificateOfEligibilityIssueDate;
    @XmlElement(name = "CertificateOfEligibilityExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar certificateOfEligibilityExpirationDate;
    @XmlElement(name = "CertificateOfEligibilityProgramName")
    protected String certificateOfEligibilityProgramName;
    @XmlElement(name = "CertificateOfEligibilitySchoolName")
    protected String certificateOfEligibilitySchoolName;
    @XmlElement(name = "CertificateOfEligibilitySchoolCode")
    protected String certificateOfEligibilitySchoolCode;
    @XmlElement(name = "ExchangeVisitorPositionCode")
    protected String exchangeVisitorPositionCode;

    /**
     * Gets the value of the certificateOfEligibilityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfEligibilityID() {
        return certificateOfEligibilityID;
    }

    /**
     * Sets the value of the certificateOfEligibilityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfEligibilityID(String value) {
        this.certificateOfEligibilityID = value;
    }

    /**
     * Gets the value of the certificateOfEligibilityIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificateOfEligibilityIssueDate() {
        return certificateOfEligibilityIssueDate;
    }

    /**
     * Sets the value of the certificateOfEligibilityIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificateOfEligibilityIssueDate(XMLGregorianCalendar value) {
        this.certificateOfEligibilityIssueDate = value;
    }

    /**
     * Gets the value of the certificateOfEligibilityExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificateOfEligibilityExpirationDate() {
        return certificateOfEligibilityExpirationDate;
    }

    /**
     * Sets the value of the certificateOfEligibilityExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificateOfEligibilityExpirationDate(XMLGregorianCalendar value) {
        this.certificateOfEligibilityExpirationDate = value;
    }

    /**
     * Gets the value of the certificateOfEligibilityProgramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfEligibilityProgramName() {
        return certificateOfEligibilityProgramName;
    }

    /**
     * Sets the value of the certificateOfEligibilityProgramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfEligibilityProgramName(String value) {
        this.certificateOfEligibilityProgramName = value;
    }

    /**
     * Gets the value of the certificateOfEligibilitySchoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfEligibilitySchoolName() {
        return certificateOfEligibilitySchoolName;
    }

    /**
     * Sets the value of the certificateOfEligibilitySchoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfEligibilitySchoolName(String value) {
        this.certificateOfEligibilitySchoolName = value;
    }

    /**
     * Gets the value of the certificateOfEligibilitySchoolCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfEligibilitySchoolCode() {
        return certificateOfEligibilitySchoolCode;
    }

    /**
     * Sets the value of the certificateOfEligibilitySchoolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfEligibilitySchoolCode(String value) {
        this.certificateOfEligibilitySchoolCode = value;
    }

    /**
     * Gets the value of the exchangeVisitorPositionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeVisitorPositionCode() {
        return exchangeVisitorPositionCode;
    }

    /**
     * Sets the value of the exchangeVisitorPositionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeVisitorPositionCode(String value) {
        this.exchangeVisitorPositionCode = value;
    }

}
