//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassRankType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassRankType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassSize" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassSizeType" minOccurs="0"/>
 *         &lt;element name="ClassRank" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassRankType" minOccurs="0"/>
 *         &lt;element name="ClassPercentileRank" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassPercentileRankType" minOccurs="0"/>
 *         &lt;element name="ClassRankOther" type="{urn:org:pesc:core:CoreMain:v1.14.0}ClassRankOtherType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassRankType", propOrder = {
    "classSize",
    "classRank",
    "classPercentileRank",
    "classRankOther"
})
public class ClassRankType {

    @XmlElement(name = "ClassSize")
    @XmlSchemaType(name = "integer")
    protected Integer classSize;
    @XmlElement(name = "ClassRank")
    @XmlSchemaType(name = "integer")
    protected Integer classRank;
    @XmlElement(name = "ClassPercentileRank")
    protected Integer classPercentileRank;
    @XmlElement(name = "ClassRankOther")
    protected String classRankOther;

    /**
     * Gets the value of the classSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassSize() {
        return classSize;
    }

    /**
     * Sets the value of the classSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassSize(Integer value) {
        this.classSize = value;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassRank(Integer value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the classPercentileRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassPercentileRank() {
        return classPercentileRank;
    }

    /**
     * Sets the value of the classPercentileRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassPercentileRank(Integer value) {
        this.classPercentileRank = value;
    }

    /**
     * Gets the value of the classRankOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassRankOther() {
        return classRankOther;
    }

    /**
     * Sets the value of the classRankOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassRankOther(String value) {
        this.classRankOther = value;
    }

}
