//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.EducationSubtestCodeType;


/**
 * Education Subtest Type
 * 
 * <p>Java class for EducationSubtestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EducationSubtestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationSubtestCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}EducationSubtestCodeType" minOccurs="0"/>
 *         &lt;element name="SubtestName" type="{urn:org:pesc:core:CoreMain:v1.14.0}SubtestNameType" minOccurs="0"/>
 *         &lt;element name="ScoreValue" type="{urn:org:pesc:core:CoreMain:v1.14.0}ScoreValueType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EducationSubtestType", propOrder = {
    "educationSubtestCode",
    "subtestName",
    "scoreValue",
    "noteMessage"
})
public class EducationSubtestType {

    @XmlElement(name = "EducationSubtestCode")
    @XmlSchemaType(name = "string")
    protected EducationSubtestCodeType educationSubtestCode;
    @XmlElement(name = "SubtestName")
    protected String subtestName;
    @XmlElement(name = "ScoreValue")
    protected String scoreValue;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the educationSubtestCode property.
     * 
     * @return
     *     possible object is
     *     {@link EducationSubtestCodeType }
     *     
     */
    public EducationSubtestCodeType getEducationSubtestCode() {
        return educationSubtestCode;
    }

    /**
     * Sets the value of the educationSubtestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationSubtestCodeType }
     *     
     */
    public void setEducationSubtestCode(EducationSubtestCodeType value) {
        this.educationSubtestCode = value;
    }

    /**
     * Gets the value of the subtestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtestName() {
        return subtestName;
    }

    /**
     * Sets the value of the subtestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtestName(String value) {
        this.subtestName = value;
    }

    /**
     * Gets the value of the scoreValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreValue() {
        return scoreValue;
    }

    /**
     * Sets the value of the scoreValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreValue(String value) {
        this.scoreValue = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
