//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.LeadershipCharacteristicCodeType;
import org.pesc.core.coremain.v1_14.StudentActivityCodeType;
import org.pesc.core.coremain.v1_14.StudentActivityGradeLevelType;
import org.pesc.core.coremain.v1_14.StudentActivityScopeCodeType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * <p>Java class for ExtraCurricularActivityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtraCurricularActivityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActivityCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentActivityCodeType" minOccurs="0"/>
 *         &lt;element name="ActivityDescription" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentActivityDescriptionType" minOccurs="0"/>
 *         &lt;element name="GradeLevel" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentActivityGradeLevelType" minOccurs="0"/>
 *         &lt;element name="YearMonthBegin" type="{urn:org:pesc:core:CoreMain:v1.14.0}YearMonthType" minOccurs="0"/>
 *         &lt;element name="YearMonthEnd" type="{urn:org:pesc:core:CoreMain:v1.14.0}YearMonthType" minOccurs="0"/>
 *         &lt;element name="Years" type="{urn:org:pesc:core:CoreMain:v1.14.0}NumberOfYearsType" minOccurs="0"/>
 *         &lt;element name="WeeklyHours" type="{urn:org:pesc:core:CoreMain:v1.14.0}WeeklyHoursType" minOccurs="0"/>
 *         &lt;element name="YearlyWeeks" type="{urn:org:pesc:core:CoreMain:v1.14.0}YearlyWeeksType" minOccurs="0"/>
 *         &lt;element name="Recognitions" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentActivityRecognitionsType" minOccurs="0"/>
 *         &lt;element name="ActivityScopeCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentActivityScopeCodeType" minOccurs="0"/>
 *         &lt;element name="ActivitySponsorOrganizationName" type="{urn:org:pesc:core:CoreMain:v1.14.0}OrganizationNameType" minOccurs="0"/>
 *         &lt;element name="LeadershipPosition" type="{urn:org:pesc:core:CoreMain:v1.14.0}LeadershipPositionType" minOccurs="0"/>
 *         &lt;element name="LeadershipCharacteristicCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}LeadershipCharacteristicCodeType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtraCurricularActivityType", propOrder = {
    "activityCode",
    "activityDescription",
    "gradeLevel",
    "yearMonthBegin",
    "yearMonthEnd",
    "years",
    "weeklyHours",
    "yearlyWeeks",
    "recognitions",
    "activityScopeCode",
    "activitySponsorOrganizationName",
    "leadershipPosition",
    "leadershipCharacteristicCode",
    "userDefinedExtensions",
    "noteMessage"
})
public class ExtraCurricularActivityType {

    @XmlElement(name = "ActivityCode")
    @XmlSchemaType(name = "string")
    protected StudentActivityCodeType activityCode;
    @XmlElement(name = "ActivityDescription")
    protected String activityDescription;
    @XmlElement(name = "GradeLevel")
    @XmlSchemaType(name = "string")
    protected StudentActivityGradeLevelType gradeLevel;
    @XmlElement(name = "YearMonthBegin")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar yearMonthBegin;
    @XmlElement(name = "YearMonthEnd")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar yearMonthEnd;
    @XmlElement(name = "Years")
    protected Integer years;
    @XmlElement(name = "WeeklyHours")
    protected Integer weeklyHours;
    @XmlElement(name = "YearlyWeeks")
    protected Integer yearlyWeeks;
    @XmlElement(name = "Recognitions")
    protected String recognitions;
    @XmlElement(name = "ActivityScopeCode")
    @XmlSchemaType(name = "string")
    protected StudentActivityScopeCodeType activityScopeCode;
    @XmlElement(name = "ActivitySponsorOrganizationName")
    protected String activitySponsorOrganizationName;
    @XmlElement(name = "LeadershipPosition")
    protected String leadershipPosition;
    @XmlElement(name = "LeadershipCharacteristicCode")
    @XmlSchemaType(name = "string")
    protected LeadershipCharacteristicCodeType leadershipCharacteristicCode;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the activityCode property.
     * 
     * @return
     *     possible object is
     *     {@link StudentActivityCodeType }
     *     
     */
    public StudentActivityCodeType getActivityCode() {
        return activityCode;
    }

    /**
     * Sets the value of the activityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentActivityCodeType }
     *     
     */
    public void setActivityCode(StudentActivityCodeType value) {
        this.activityCode = value;
    }

    /**
     * Gets the value of the activityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDescription() {
        return activityDescription;
    }

    /**
     * Sets the value of the activityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDescription(String value) {
        this.activityDescription = value;
    }

    /**
     * Gets the value of the gradeLevel property.
     * 
     * @return
     *     possible object is
     *     {@link StudentActivityGradeLevelType }
     *     
     */
    public StudentActivityGradeLevelType getGradeLevel() {
        return gradeLevel;
    }

    /**
     * Sets the value of the gradeLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentActivityGradeLevelType }
     *     
     */
    public void setGradeLevel(StudentActivityGradeLevelType value) {
        this.gradeLevel = value;
    }

    /**
     * Gets the value of the yearMonthBegin property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYearMonthBegin() {
        return yearMonthBegin;
    }

    /**
     * Sets the value of the yearMonthBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYearMonthBegin(XMLGregorianCalendar value) {
        this.yearMonthBegin = value;
    }

    /**
     * Gets the value of the yearMonthEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYearMonthEnd() {
        return yearMonthEnd;
    }

    /**
     * Sets the value of the yearMonthEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYearMonthEnd(XMLGregorianCalendar value) {
        this.yearMonthEnd = value;
    }

    /**
     * Gets the value of the years property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYears() {
        return years;
    }

    /**
     * Sets the value of the years property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYears(Integer value) {
        this.years = value;
    }

    /**
     * Gets the value of the weeklyHours property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeeklyHours() {
        return weeklyHours;
    }

    /**
     * Sets the value of the weeklyHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeeklyHours(Integer value) {
        this.weeklyHours = value;
    }

    /**
     * Gets the value of the yearlyWeeks property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYearlyWeeks() {
        return yearlyWeeks;
    }

    /**
     * Sets the value of the yearlyWeeks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYearlyWeeks(Integer value) {
        this.yearlyWeeks = value;
    }

    /**
     * Gets the value of the recognitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecognitions() {
        return recognitions;
    }

    /**
     * Sets the value of the recognitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecognitions(String value) {
        this.recognitions = value;
    }

    /**
     * Gets the value of the activityScopeCode property.
     * 
     * @return
     *     possible object is
     *     {@link StudentActivityScopeCodeType }
     *     
     */
    public StudentActivityScopeCodeType getActivityScopeCode() {
        return activityScopeCode;
    }

    /**
     * Sets the value of the activityScopeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentActivityScopeCodeType }
     *     
     */
    public void setActivityScopeCode(StudentActivityScopeCodeType value) {
        this.activityScopeCode = value;
    }

    /**
     * Gets the value of the activitySponsorOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivitySponsorOrganizationName() {
        return activitySponsorOrganizationName;
    }

    /**
     * Sets the value of the activitySponsorOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivitySponsorOrganizationName(String value) {
        this.activitySponsorOrganizationName = value;
    }

    /**
     * Gets the value of the leadershipPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadershipPosition() {
        return leadershipPosition;
    }

    /**
     * Sets the value of the leadershipPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadershipPosition(String value) {
        this.leadershipPosition = value;
    }

    /**
     * Gets the value of the leadershipCharacteristicCode property.
     * 
     * @return
     *     possible object is
     *     {@link LeadershipCharacteristicCodeType }
     *     
     */
    public LeadershipCharacteristicCodeType getLeadershipCharacteristicCode() {
        return leadershipCharacteristicCode;
    }

    /**
     * Sets the value of the leadershipCharacteristicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeadershipCharacteristicCodeType }
     *     
     */
    public void setLeadershipCharacteristicCode(LeadershipCharacteristicCodeType value) {
        this.leadershipCharacteristicCode = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
