//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.ParentsMaritalStatusCodeType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * Family Type
 * 
 * <p>Java class for FamilyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FamilyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentsMaritalStatusCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}ParentsMaritalStatusCodeType" minOccurs="0"/>
 *         &lt;element name="FamilyMember" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AdmissionsPersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FamilyLegacy" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}FamilyLegacyType" minOccurs="0"/>
 *         &lt;element name="FamilyIncome" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}FamilyIncomeType" minOccurs="0"/>
 *         &lt;element name="FamilyDependents" type="{urn:org:pesc:core:CoreMain:v1.14.0}FamilyDependentsNumberType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FamilyType", propOrder = {
    "parentsMaritalStatusCode",
    "familyMember",
    "familyLegacy",
    "familyIncome",
    "familyDependents",
    "userDefinedExtensions",
    "noteMessage"
})
public class FamilyType {

    @XmlElement(name = "ParentsMaritalStatusCode")
    @XmlSchemaType(name = "string")
    protected ParentsMaritalStatusCodeType parentsMaritalStatusCode;
    @XmlElement(name = "FamilyMember")
    protected List<AdmissionsPersonType> familyMember;
    @XmlElement(name = "FamilyLegacy")
    protected FamilyLegacyType familyLegacy;
    @XmlElement(name = "FamilyIncome")
    protected FamilyIncomeType familyIncome;
    @XmlElement(name = "FamilyDependents")
    protected Integer familyDependents;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the parentsMaritalStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link ParentsMaritalStatusCodeType }
     *     
     */
    public ParentsMaritalStatusCodeType getParentsMaritalStatusCode() {
        return parentsMaritalStatusCode;
    }

    /**
     * Sets the value of the parentsMaritalStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentsMaritalStatusCodeType }
     *     
     */
    public void setParentsMaritalStatusCode(ParentsMaritalStatusCodeType value) {
        this.parentsMaritalStatusCode = value;
    }

    /**
     * Gets the value of the familyMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the familyMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFamilyMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdmissionsPersonType }
     * 
     * 
     */
    public List<AdmissionsPersonType> getFamilyMember() {
        if (familyMember == null) {
            familyMember = new ArrayList<AdmissionsPersonType>();
        }
        return this.familyMember;
    }

    /**
     * Gets the value of the familyLegacy property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyLegacyType }
     *     
     */
    public FamilyLegacyType getFamilyLegacy() {
        return familyLegacy;
    }

    /**
     * Sets the value of the familyLegacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyLegacyType }
     *     
     */
    public void setFamilyLegacy(FamilyLegacyType value) {
        this.familyLegacy = value;
    }

    /**
     * Gets the value of the familyIncome property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyIncomeType }
     *     
     */
    public FamilyIncomeType getFamilyIncome() {
        return familyIncome;
    }

    /**
     * Sets the value of the familyIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyIncomeType }
     *     
     */
    public void setFamilyIncome(FamilyIncomeType value) {
        this.familyIncome = value;
    }

    /**
     * Gets the value of the familyDependents property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFamilyDependents() {
        return familyDependents;
    }

    /**
     * Sets the value of the familyDependents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFamilyDependents(Integer value) {
        this.familyDependents = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
