//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.DependencyStatusCodeType;


/**
 * <p>Java class for FinancialDependencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialDependencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DependencyStatusCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DependencyStatusCodeType" minOccurs="0"/>
 *         &lt;element name="FinancialDependencyDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}FinancialDependencyDateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialDependencyType", propOrder = {
    "dependencyStatusCode",
    "financialDependencyDate"
})
public class FinancialDependencyType {

    @XmlElement(name = "DependencyStatusCode")
    @XmlSchemaType(name = "string")
    protected DependencyStatusCodeType dependencyStatusCode;
    @XmlElement(name = "FinancialDependencyDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar financialDependencyDate;

    /**
     * Gets the value of the dependencyStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyStatusCodeType }
     *     
     */
    public DependencyStatusCodeType getDependencyStatusCode() {
        return dependencyStatusCode;
    }

    /**
     * Sets the value of the dependencyStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyStatusCodeType }
     *     
     */
    public void setDependencyStatusCode(DependencyStatusCodeType value) {
        this.dependencyStatusCode = value;
    }

    /**
     * Gets the value of the financialDependencyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinancialDependencyDate() {
        return financialDependencyDate;
    }

    /**
     * Sets the value of the financialDependencyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinancialDependencyDate(XMLGregorianCalendar value) {
        this.financialDependencyDate = value;
    }

}
