//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.ContactsType;
import org.pesc.core.coremain.v1_14.CountryCodeType;
import org.pesc.core.coremain.v1_14.FundingSourceCodeType;


/**
 * <p>Java class for FundingSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FundingSourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FundingAmount" type="{urn:org:pesc:core:CoreMain:v1.14.0}FundingAmountType" minOccurs="0"/>
 *         &lt;element name="FundingSourceCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}FundingSourceCodeType" minOccurs="0"/>
 *         &lt;element name="FundingSourceName" type="{urn:org:pesc:core:CoreMain:v1.14.0}FundingSourceNameType" minOccurs="0"/>
 *         &lt;element name="FundingSourceCountry" type="{urn:org:pesc:core:CoreMain:v1.14.0}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="FundingSourceContact" type="{urn:org:pesc:core:CoreMain:v1.14.0}ContactsType" minOccurs="0"/>
 *         &lt;element name="StartingYearMonth" type="{urn:org:pesc:core:CoreMain:v1.14.0}YearMonthType" minOccurs="0"/>
 *         &lt;element name="EndingYearMonth" type="{urn:org:pesc:core:CoreMain:v1.14.0}YearMonthType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FundingSourceType", propOrder = {
    "fundingAmount",
    "fundingSourceCode",
    "fundingSourceName",
    "fundingSourceCountry",
    "fundingSourceContact",
    "startingYearMonth",
    "endingYearMonth"
})
public class FundingSourceType {

    @XmlElement(name = "FundingAmount")
    protected Integer fundingAmount;
    @XmlElement(name = "FundingSourceCode")
    @XmlSchemaType(name = "string")
    protected FundingSourceCodeType fundingSourceCode;
    @XmlElement(name = "FundingSourceName")
    protected String fundingSourceName;
    @XmlElement(name = "FundingSourceCountry")
    @XmlSchemaType(name = "string")
    protected CountryCodeType fundingSourceCountry;
    @XmlElement(name = "FundingSourceContact")
    protected ContactsType fundingSourceContact;
    @XmlElement(name = "StartingYearMonth")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar startingYearMonth;
    @XmlElement(name = "EndingYearMonth")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar endingYearMonth;

    /**
     * Gets the value of the fundingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFundingAmount() {
        return fundingAmount;
    }

    /**
     * Sets the value of the fundingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFundingAmount(Integer value) {
        this.fundingAmount = value;
    }

    /**
     * Gets the value of the fundingSourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link FundingSourceCodeType }
     *     
     */
    public FundingSourceCodeType getFundingSourceCode() {
        return fundingSourceCode;
    }

    /**
     * Sets the value of the fundingSourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingSourceCodeType }
     *     
     */
    public void setFundingSourceCode(FundingSourceCodeType value) {
        this.fundingSourceCode = value;
    }

    /**
     * Gets the value of the fundingSourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundingSourceName() {
        return fundingSourceName;
    }

    /**
     * Sets the value of the fundingSourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundingSourceName(String value) {
        this.fundingSourceName = value;
    }

    /**
     * Gets the value of the fundingSourceCountry property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getFundingSourceCountry() {
        return fundingSourceCountry;
    }

    /**
     * Sets the value of the fundingSourceCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setFundingSourceCountry(CountryCodeType value) {
        this.fundingSourceCountry = value;
    }

    /**
     * Gets the value of the fundingSourceContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactsType }
     *     
     */
    public ContactsType getFundingSourceContact() {
        return fundingSourceContact;
    }

    /**
     * Sets the value of the fundingSourceContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactsType }
     *     
     */
    public void setFundingSourceContact(ContactsType value) {
        this.fundingSourceContact = value;
    }

    /**
     * Gets the value of the startingYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartingYearMonth() {
        return startingYearMonth;
    }

    /**
     * Sets the value of the startingYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartingYearMonth(XMLGregorianCalendar value) {
        this.startingYearMonth = value;
    }

    /**
     * Gets the value of the endingYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndingYearMonth() {
        return endingYearMonth;
    }

    /**
     * Sets the value of the endingYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndingYearMonth(XMLGregorianCalendar value) {
        this.endingYearMonth = value;
    }

}
