//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.HousingInformationCodeType;


/**
 * <p>Java class for HousingInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HousingInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HousingInformationCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}HousingInformationCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HousingInformationType", propOrder = {
    "housingInformationCode"
})
public class HousingInformationType {

    @XmlElement(name = "HousingInformationCode")
    @XmlSchemaType(name = "string")
    protected List<HousingInformationCodeType> housingInformationCode;

    /**
     * Gets the value of the housingInformationCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the housingInformationCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHousingInformationCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HousingInformationCodeType }
     * 
     * 
     */
    public List<HousingInformationCodeType> getHousingInformationCode() {
        if (housingInformationCode == null) {
            housingInformationCode = new ArrayList<HousingInformationCodeType>();
        }
        return this.housingInformationCode;
    }

}
