//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.CurrentlyInUSCodeType;


/**
 * <p>Java class for ImmigrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImmigrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlienRegistrationNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}AlienRegistrationNumberType" minOccurs="0"/>
 *         &lt;element name="AsyleeRefugee" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AsyleeRefugeeType" minOccurs="0"/>
 *         &lt;element name="PermanentResident" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}PermanentResidentType" minOccurs="0"/>
 *         &lt;element name="FirstEntryIntoHostCountryDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}FirstEntryIntoUSDateType" minOccurs="0"/>
 *         &lt;element name="ImmigrationI20RequestIndicator" type="{urn:org:pesc:core:CoreMain:v1.14.0}ImmigrationI20RequestIndicatorType" minOccurs="0"/>
 *         &lt;element name="CertificateOfEligibilityDetail" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}CertificateOfEligibilityDetailType" minOccurs="0"/>
 *         &lt;element name="Sponsor" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}SponsorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PassportDetail" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}PassportDetailType" minOccurs="0"/>
 *         &lt;element name="VisaDetail" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}VisaDetailType" minOccurs="0"/>
 *         &lt;element name="I94Detail" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}I94DetailType" minOccurs="0"/>
 *         &lt;element name="Dependent" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}DependentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OptionalPracticalTraining" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}OptionalPracticalTrainingType" minOccurs="0"/>
 *         &lt;element name="CurricularPracticalTraining" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}CurricularPracticalTrainingType" minOccurs="0"/>
 *         &lt;element name="AcademicTraining" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}AcademicTrainingType" minOccurs="0"/>
 *         &lt;element name="CurrentlyInUSCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CurrentlyInUSCodeType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImmigrationType", propOrder = {
    "alienRegistrationNumber",
    "asyleeRefugee",
    "permanentResident",
    "firstEntryIntoHostCountryDate",
    "immigrationI20RequestIndicator",
    "certificateOfEligibilityDetail",
    "sponsor",
    "passportDetail",
    "visaDetail",
    "i94Detail",
    "dependent",
    "optionalPracticalTraining",
    "curricularPracticalTraining",
    "academicTraining",
    "currentlyInUSCode",
    "noteMessage"
})
public class ImmigrationType {

    @XmlElement(name = "AlienRegistrationNumber")
    protected String alienRegistrationNumber;
    @XmlElement(name = "AsyleeRefugee")
    protected AsyleeRefugeeType asyleeRefugee;
    @XmlElement(name = "PermanentResident")
    protected PermanentResidentType permanentResident;
    @XmlElement(name = "FirstEntryIntoHostCountryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstEntryIntoHostCountryDate;
    @XmlElement(name = "ImmigrationI20RequestIndicator")
    protected Boolean immigrationI20RequestIndicator;
    @XmlElement(name = "CertificateOfEligibilityDetail")
    protected CertificateOfEligibilityDetailType certificateOfEligibilityDetail;
    @XmlElement(name = "Sponsor")
    protected List<SponsorType> sponsor;
    @XmlElement(name = "PassportDetail")
    protected PassportDetailType passportDetail;
    @XmlElement(name = "VisaDetail")
    protected VisaDetailType visaDetail;
    @XmlElement(name = "I94Detail")
    protected I94DetailType i94Detail;
    @XmlElement(name = "Dependent")
    protected List<DependentType> dependent;
    @XmlElement(name = "OptionalPracticalTraining")
    protected OptionalPracticalTrainingType optionalPracticalTraining;
    @XmlElement(name = "CurricularPracticalTraining")
    protected CurricularPracticalTrainingType curricularPracticalTraining;
    @XmlElement(name = "AcademicTraining")
    protected AcademicTrainingType academicTraining;
    @XmlElement(name = "CurrentlyInUSCode")
    @XmlSchemaType(name = "string")
    protected CurrentlyInUSCodeType currentlyInUSCode;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the alienRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlienRegistrationNumber() {
        return alienRegistrationNumber;
    }

    /**
     * Sets the value of the alienRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlienRegistrationNumber(String value) {
        this.alienRegistrationNumber = value;
    }

    /**
     * Gets the value of the asyleeRefugee property.
     * 
     * @return
     *     possible object is
     *     {@link AsyleeRefugeeType }
     *     
     */
    public AsyleeRefugeeType getAsyleeRefugee() {
        return asyleeRefugee;
    }

    /**
     * Sets the value of the asyleeRefugee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsyleeRefugeeType }
     *     
     */
    public void setAsyleeRefugee(AsyleeRefugeeType value) {
        this.asyleeRefugee = value;
    }

    /**
     * Gets the value of the permanentResident property.
     * 
     * @return
     *     possible object is
     *     {@link PermanentResidentType }
     *     
     */
    public PermanentResidentType getPermanentResident() {
        return permanentResident;
    }

    /**
     * Sets the value of the permanentResident property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermanentResidentType }
     *     
     */
    public void setPermanentResident(PermanentResidentType value) {
        this.permanentResident = value;
    }

    /**
     * Gets the value of the firstEntryIntoHostCountryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstEntryIntoHostCountryDate() {
        return firstEntryIntoHostCountryDate;
    }

    /**
     * Sets the value of the firstEntryIntoHostCountryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstEntryIntoHostCountryDate(XMLGregorianCalendar value) {
        this.firstEntryIntoHostCountryDate = value;
    }

    /**
     * Gets the value of the immigrationI20RequestIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImmigrationI20RequestIndicator() {
        return immigrationI20RequestIndicator;
    }

    /**
     * Sets the value of the immigrationI20RequestIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImmigrationI20RequestIndicator(Boolean value) {
        this.immigrationI20RequestIndicator = value;
    }

    /**
     * Gets the value of the certificateOfEligibilityDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateOfEligibilityDetailType }
     *     
     */
    public CertificateOfEligibilityDetailType getCertificateOfEligibilityDetail() {
        return certificateOfEligibilityDetail;
    }

    /**
     * Sets the value of the certificateOfEligibilityDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateOfEligibilityDetailType }
     *     
     */
    public void setCertificateOfEligibilityDetail(CertificateOfEligibilityDetailType value) {
        this.certificateOfEligibilityDetail = value;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SponsorType }
     * 
     * 
     */
    public List<SponsorType> getSponsor() {
        if (sponsor == null) {
            sponsor = new ArrayList<SponsorType>();
        }
        return this.sponsor;
    }

    /**
     * Gets the value of the passportDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PassportDetailType }
     *     
     */
    public PassportDetailType getPassportDetail() {
        return passportDetail;
    }

    /**
     * Sets the value of the passportDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportDetailType }
     *     
     */
    public void setPassportDetail(PassportDetailType value) {
        this.passportDetail = value;
    }

    /**
     * Gets the value of the visaDetail property.
     * 
     * @return
     *     possible object is
     *     {@link VisaDetailType }
     *     
     */
    public VisaDetailType getVisaDetail() {
        return visaDetail;
    }

    /**
     * Sets the value of the visaDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisaDetailType }
     *     
     */
    public void setVisaDetail(VisaDetailType value) {
        this.visaDetail = value;
    }

    /**
     * Gets the value of the i94Detail property.
     * 
     * @return
     *     possible object is
     *     {@link I94DetailType }
     *     
     */
    public I94DetailType getI94Detail() {
        return i94Detail;
    }

    /**
     * Sets the value of the i94Detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link I94DetailType }
     *     
     */
    public void setI94Detail(I94DetailType value) {
        this.i94Detail = value;
    }

    /**
     * Gets the value of the dependent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DependentType }
     * 
     * 
     */
    public List<DependentType> getDependent() {
        if (dependent == null) {
            dependent = new ArrayList<DependentType>();
        }
        return this.dependent;
    }

    /**
     * Gets the value of the optionalPracticalTraining property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalPracticalTrainingType }
     *     
     */
    public OptionalPracticalTrainingType getOptionalPracticalTraining() {
        return optionalPracticalTraining;
    }

    /**
     * Sets the value of the optionalPracticalTraining property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalPracticalTrainingType }
     *     
     */
    public void setOptionalPracticalTraining(OptionalPracticalTrainingType value) {
        this.optionalPracticalTraining = value;
    }

    /**
     * Gets the value of the curricularPracticalTraining property.
     * 
     * @return
     *     possible object is
     *     {@link CurricularPracticalTrainingType }
     *     
     */
    public CurricularPracticalTrainingType getCurricularPracticalTraining() {
        return curricularPracticalTraining;
    }

    /**
     * Sets the value of the curricularPracticalTraining property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurricularPracticalTrainingType }
     *     
     */
    public void setCurricularPracticalTraining(CurricularPracticalTrainingType value) {
        this.curricularPracticalTraining = value;
    }

    /**
     * Gets the value of the academicTraining property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicTrainingType }
     *     
     */
    public AcademicTrainingType getAcademicTraining() {
        return academicTraining;
    }

    /**
     * Sets the value of the academicTraining property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicTrainingType }
     *     
     */
    public void setAcademicTraining(AcademicTrainingType value) {
        this.academicTraining = value;
    }

    /**
     * Gets the value of the currentlyInUSCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentlyInUSCodeType }
     *     
     */
    public CurrentlyInUSCodeType getCurrentlyInUSCode() {
        return currentlyInUSCode;
    }

    /**
     * Sets the value of the currentlyInUSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentlyInUSCodeType }
     *     
     */
    public void setCurrentlyInUSCode(CurrentlyInUSCodeType value) {
        this.currentlyInUSCode = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
