//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.StateProvinceCodeType;


/**
 * <p>Java class for IncomeTaxInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncomeTaxInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncomeTaxState" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType" minOccurs="0"/>
 *         &lt;element name="IncomeTaxYear" type="{urn:org:pesc:core:CoreMain:v1.14.0}IncomeTaxYearType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncomeTaxInformationType", propOrder = {
    "incomeTaxState",
    "incomeTaxYear"
})
public class IncomeTaxInformationType {

    @XmlElement(name = "IncomeTaxState")
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType incomeTaxState;
    @XmlElement(name = "IncomeTaxYear")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar incomeTaxYear;

    /**
     * Gets the value of the incomeTaxState property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getIncomeTaxState() {
        return incomeTaxState;
    }

    /**
     * Sets the value of the incomeTaxState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setIncomeTaxState(StateProvinceCodeType value) {
        this.incomeTaxState = value;
    }

    /**
     * Gets the value of the incomeTaxYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIncomeTaxYear() {
        return incomeTaxYear;
    }

    /**
     * Sets the value of the incomeTaxYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIncomeTaxYear(XMLGregorianCalendar value) {
        this.incomeTaxYear = value;
    }

}
