//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstantMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstantMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstantMessageAddress" type="{urn:org:pesc:core:CoreMain:v1.14.0}InstantMessageAddressType"/>
 *         &lt;element name="InstantMessageProviderName" type="{urn:org:pesc:core:CoreMain:v1.14.0}InstantMessageProviderNameType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstantMessageType", propOrder = {
    "instantMessageAddress",
    "instantMessageProviderName"
})
public class InstantMessageType {

    @XmlElement(name = "InstantMessageAddress", required = true)
    protected String instantMessageAddress;
    @XmlElement(name = "InstantMessageProviderName")
    protected String instantMessageProviderName;

    /**
     * Gets the value of the instantMessageAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstantMessageAddress() {
        return instantMessageAddress;
    }

    /**
     * Sets the value of the instantMessageAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstantMessageAddress(String value) {
        this.instantMessageAddress = value;
    }

    /**
     * Gets the value of the instantMessageProviderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstantMessageProviderName() {
        return instantMessageProviderName;
    }

    /**
     * Sets the value of the instantMessageProviderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstantMessageProviderName(String value) {
        this.instantMessageProviderName = value;
    }

}
