//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.pesc.sector.admissionsrecord.v1_3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.pesc.sector.admissionsrecord.v1_3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransmissionDataType }
     * 
     */
    public TransmissionDataType createTransmissionDataType() {
        return new TransmissionDataType();
    }

    /**
     * Create an instance of {@link ApplicantType }
     * 
     */
    public ApplicantType createApplicantType() {
        return new ApplicantType();
    }

    /**
     * Create an instance of {@link FundingSourceType }
     * 
     */
    public FundingSourceType createFundingSourceType() {
        return new FundingSourceType();
    }

    /**
     * Create an instance of {@link AcademicAwardType }
     * 
     */
    public AcademicAwardType createAcademicAwardType() {
        return new AcademicAwardType();
    }

    /**
     * Create an instance of {@link I94DetailType }
     * 
     */
    public I94DetailType createI94DetailType() {
        return new I94DetailType();
    }

    /**
     * Create an instance of {@link AcademicTrainingType }
     * 
     */
    public AcademicTrainingType createAcademicTrainingType() {
        return new AcademicTrainingType();
    }

    /**
     * Create an instance of {@link ImmigrationType }
     * 
     */
    public ImmigrationType createImmigrationType() {
        return new ImmigrationType();
    }

    /**
     * Create an instance of {@link TransmissionOrganizationType }
     * 
     */
    public TransmissionOrganizationType createTransmissionOrganizationType() {
        return new TransmissionOrganizationType();
    }

    /**
     * Create an instance of {@link CertificateOfEligibilityDetailType }
     * 
     */
    public CertificateOfEligibilityDetailType createCertificateOfEligibilityDetailType() {
        return new CertificateOfEligibilityDetailType();
    }

    /**
     * Create an instance of {@link OptionalPracticalTrainingType }
     * 
     */
    public OptionalPracticalTrainingType createOptionalPracticalTrainingType() {
        return new OptionalPracticalTrainingType();
    }

    /**
     * Create an instance of {@link StudentEmploymentType }
     * 
     */
    public StudentEmploymentType createStudentEmploymentType() {
        return new StudentEmploymentType();
    }

    /**
     * Create an instance of {@link FamilyIncomeType }
     * 
     */
    public FamilyIncomeType createFamilyIncomeType() {
        return new FamilyIncomeType();
    }

    /**
     * Create an instance of {@link AdditionalStudentAchievementsType }
     * 
     */
    public AdditionalStudentAchievementsType createAdditionalStudentAchievementsType() {
        return new AdditionalStudentAchievementsType();
    }

    /**
     * Create an instance of {@link PreviousApplicationType }
     * 
     */
    public PreviousApplicationType createPreviousApplicationType() {
        return new PreviousApplicationType();
    }

    /**
     * Create an instance of {@link FinancialDependencyType }
     * 
     */
    public FinancialDependencyType createFinancialDependencyType() {
        return new FinancialDependencyType();
    }

    /**
     * Create an instance of {@link AcademicProgramDetailType }
     * 
     */
    public AcademicProgramDetailType createAcademicProgramDetailType() {
        return new AcademicProgramDetailType();
    }

    /**
     * Create an instance of {@link ExtraCurricularActivityType }
     * 
     */
    public ExtraCurricularActivityType createExtraCurricularActivityType() {
        return new ExtraCurricularActivityType();
    }

    /**
     * Create an instance of {@link AcademicSummaryType }
     * 
     */
    public AcademicSummaryType createAcademicSummaryType() {
        return new AcademicSummaryType();
    }

    /**
     * Create an instance of {@link PropertyOwnedType }
     * 
     */
    public PropertyOwnedType createPropertyOwnedType() {
        return new PropertyOwnedType();
    }

    /**
     * Create an instance of {@link OtherStudentAchievementType }
     * 
     */
    public OtherStudentAchievementType createOtherStudentAchievementType() {
        return new OtherStudentAchievementType();
    }

    /**
     * Create an instance of {@link LegacyType }
     * 
     */
    public LegacyType createLegacyType() {
        return new LegacyType();
    }

    /**
     * Create an instance of {@link ApplicantPersonType }
     * 
     */
    public ApplicantPersonType createApplicantPersonType() {
        return new ApplicantPersonType();
    }

    /**
     * Create an instance of {@link HousingInformationType }
     * 
     */
    public HousingInformationType createHousingInformationType() {
        return new HousingInformationType();
    }

    /**
     * Create an instance of {@link AcademicProgramType }
     * 
     */
    public AcademicProgramType createAcademicProgramType() {
        return new AcademicProgramType();
    }

    /**
     * Create an instance of {@link ApplyDecisionType }
     * 
     */
    public ApplyDecisionType createApplyDecisionType() {
        return new ApplyDecisionType();
    }

    /**
     * Create an instance of {@link SponsorType }
     * 
     */
    public SponsorType createSponsorType() {
        return new SponsorType();
    }

    /**
     * Create an instance of {@link VisaDetailType }
     * 
     */
    public VisaDetailType createVisaDetailType() {
        return new VisaDetailType();
    }

    /**
     * Create an instance of {@link CanadianEthnicityRaceType }
     * 
     */
    public CanadianEthnicityRaceType createCanadianEthnicityRaceType() {
        return new CanadianEthnicityRaceType();
    }

    /**
     * Create an instance of {@link StateIdentificationType }
     * 
     */
    public StateIdentificationType createStateIdentificationType() {
        return new StateIdentificationType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link FamilyType }
     * 
     */
    public FamilyType createFamilyType() {
        return new FamilyType();
    }

    /**
     * Create an instance of {@link ActivityParticipationRequestType }
     * 
     */
    public ActivityParticipationRequestType createActivityParticipationRequestType() {
        return new ActivityParticipationRequestType();
    }

    /**
     * Create an instance of {@link CurricularPracticalTrainingType }
     * 
     */
    public CurricularPracticalTrainingType createCurricularPracticalTrainingType() {
        return new CurricularPracticalTrainingType();
    }

    /**
     * Create an instance of {@link VoterRegistrationType }
     * 
     */
    public VoterRegistrationType createVoterRegistrationType() {
        return new VoterRegistrationType();
    }

    /**
     * Create an instance of {@link ResidencyEmploymentType }
     * 
     */
    public ResidencyEmploymentType createResidencyEmploymentType() {
        return new ResidencyEmploymentType();
    }

    /**
     * Create an instance of {@link AcademicSessionType }
     * 
     */
    public AcademicSessionType createAcademicSessionType() {
        return new AcademicSessionType();
    }

    /**
     * Create an instance of {@link HighSchoolSubjectAreaType }
     * 
     */
    public HighSchoolSubjectAreaType createHighSchoolSubjectAreaType() {
        return new HighSchoolSubjectAreaType();
    }

    /**
     * Create an instance of {@link ClassRankType }
     * 
     */
    public ClassRankType createClassRankType() {
        return new ClassRankType();
    }

    /**
     * Create an instance of {@link DriversLicenseType }
     * 
     */
    public DriversLicenseType createDriversLicenseType() {
        return new DriversLicenseType();
    }

    /**
     * Create an instance of {@link IncomeTaxInformationType }
     * 
     */
    public IncomeTaxInformationType createIncomeTaxInformationType() {
        return new IncomeTaxInformationType();
    }

    /**
     * Create an instance of {@link AsyleeRefugeeType }
     * 
     */
    public AsyleeRefugeeType createAsyleeRefugeeType() {
        return new AsyleeRefugeeType();
    }

    /**
     * Create an instance of {@link ContactsType }
     * 
     */
    public ContactsType createContactsType() {
        return new ContactsType();
    }

    /**
     * Create an instance of {@link PassportDetailType }
     * 
     */
    public PassportDetailType createPassportDetailType() {
        return new PassportDetailType();
    }

    /**
     * Create an instance of {@link RecommendationReferenceType }
     * 
     */
    public RecommendationReferenceType createRecommendationReferenceType() {
        return new RecommendationReferenceType();
    }

    /**
     * Create an instance of {@link ActiveDutyMilitaryType }
     * 
     */
    public ActiveDutyMilitaryType createActiveDutyMilitaryType() {
        return new ActiveDutyMilitaryType();
    }

    /**
     * Create an instance of {@link AllowedAnswersType }
     * 
     */
    public AllowedAnswersType createAllowedAnswersType() {
        return new AllowedAnswersType();
    }

    /**
     * Create an instance of {@link AgencyIdentifierType }
     * 
     */
    public AgencyIdentifierType createAgencyIdentifierType() {
        return new AgencyIdentifierType();
    }

    /**
     * Create an instance of {@link OtherCollegeType }
     * 
     */
    public OtherCollegeType createOtherCollegeType() {
        return new OtherCollegeType();
    }

    /**
     * Create an instance of {@link InfoRequestedType }
     * 
     */
    public InfoRequestedType createInfoRequestedType() {
        return new InfoRequestedType();
    }

    /**
     * Create an instance of {@link OtherCollegeApplicationType }
     * 
     */
    public OtherCollegeApplicationType createOtherCollegeApplicationType() {
        return new OtherCollegeApplicationType();
    }

    /**
     * Create an instance of {@link AdmissionsPersonType }
     * 
     */
    public AdmissionsPersonType createAdmissionsPersonType() {
        return new AdmissionsPersonType();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link InstantMessageType }
     * 
     */
    public InstantMessageType createInstantMessageType() {
        return new InstantMessageType();
    }

    /**
     * Create an instance of {@link PlanToApplyForType }
     * 
     */
    public PlanToApplyForType createPlanToApplyForType() {
        return new PlanToApplyForType();
    }

    /**
     * Create an instance of {@link AcademicRecordType }
     * 
     */
    public AcademicRecordType createAcademicRecordType() {
        return new AcademicRecordType();
    }

    /**
     * Create an instance of {@link EducationSubtestType }
     * 
     */
    public EducationSubtestType createEducationSubtestType() {
        return new EducationSubtestType();
    }

    /**
     * Create an instance of {@link FamilyLegacyType }
     * 
     */
    public FamilyLegacyType createFamilyLegacyType() {
        return new FamilyLegacyType();
    }

    /**
     * Create an instance of {@link DependentType }
     * 
     */
    public DependentType createDependentType() {
        return new DependentType();
    }

    /**
     * Create an instance of {@link DecisionToApplyType }
     * 
     */
    public DecisionToApplyType createDecisionToApplyType() {
        return new DecisionToApplyType();
    }

    /**
     * Create an instance of {@link VehicleRegistrationType }
     * 
     */
    public VehicleRegistrationType createVehicleRegistrationType() {
        return new VehicleRegistrationType();
    }

    /**
     * Create an instance of {@link PublicAssistanceReceivedType }
     * 
     */
    public PublicAssistanceReceivedType createPublicAssistanceReceivedType() {
        return new PublicAssistanceReceivedType();
    }

    /**
     * Create an instance of {@link ApplicationDetailType }
     * 
     */
    public ApplicationDetailType createApplicationDetailType() {
        return new ApplicationDetailType();
    }

    /**
     * Create an instance of {@link AdmissionsApplicationQuestionType }
     * 
     */
    public AdmissionsApplicationQuestionType createAdmissionsApplicationQuestionType() {
        return new AdmissionsApplicationQuestionType();
    }

    /**
     * Create an instance of {@link ApplicationFeeType }
     * 
     */
    public ApplicationFeeType createApplicationFeeType() {
        return new ApplicationFeeType();
    }

    /**
     * Create an instance of {@link ApplicationOrganizationType }
     * 
     */
    public ApplicationOrganizationType createApplicationOrganizationType() {
        return new ApplicationOrganizationType();
    }

    /**
     * Create an instance of {@link SchoolType }
     * 
     */
    public SchoolType createSchoolType() {
        return new SchoolType();
    }

    /**
     * Create an instance of {@link SourceDestinationType }
     * 
     */
    public SourceDestinationType createSourceDestinationType() {
        return new SourceDestinationType();
    }

    /**
     * Create an instance of {@link TestsType }
     * 
     */
    public TestsType createTestsType() {
        return new TestsType();
    }

    /**
     * Create an instance of {@link PermanentResidentType }
     * 
     */
    public PermanentResidentType createPermanentResidentType() {
        return new PermanentResidentType();
    }

    /**
     * Create an instance of {@link ResidencyType }
     * 
     */
    public ResidencyType createResidencyType() {
        return new ResidencyType();
    }

}
