//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.AchievementCategoryCodeType;
import org.pesc.core.coremain.v1_14.StudentLevelCodeType;


/**
 * <p>Java class for OtherStudentAchievementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherStudentAchievementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AchievementCategoryCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}AchievementCategoryCodeType" minOccurs="0"/>
 *         &lt;element name="AchievementTitle" type="{urn:org:pesc:core:CoreMain:v1.14.0}AchievementTitleType" minOccurs="0"/>
 *         &lt;element name="SponsorName" type="{urn:org:pesc:core:CoreMain:v1.14.0}SponsorNameType" minOccurs="0"/>
 *         &lt;element name="StudentLevelCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentLevelCodeType" minOccurs="0"/>
 *         &lt;element name="AchievementAwardYear" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentAchievementAwardYearType" minOccurs="0"/>
 *         &lt;element name="AchievementAwardYearMonth" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentAchievementAwardYearMonthType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherStudentAchievementType", propOrder = {
    "achievementCategoryCode",
    "achievementTitle",
    "sponsorName",
    "studentLevelCode",
    "achievementAwardYear",
    "achievementAwardYearMonth",
    "noteMessage"
})
public class OtherStudentAchievementType {

    @XmlElement(name = "AchievementCategoryCode")
    @XmlSchemaType(name = "string")
    protected AchievementCategoryCodeType achievementCategoryCode;
    @XmlElement(name = "AchievementTitle")
    protected String achievementTitle;
    @XmlElement(name = "SponsorName")
    protected String sponsorName;
    @XmlElement(name = "StudentLevelCode")
    @XmlSchemaType(name = "string")
    protected StudentLevelCodeType studentLevelCode;
    @XmlElement(name = "AchievementAwardYear")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar achievementAwardYear;
    @XmlElement(name = "AchievementAwardYearMonth")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar achievementAwardYearMonth;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the achievementCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementCategoryCodeType }
     *     
     */
    public AchievementCategoryCodeType getAchievementCategoryCode() {
        return achievementCategoryCode;
    }

    /**
     * Sets the value of the achievementCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementCategoryCodeType }
     *     
     */
    public void setAchievementCategoryCode(AchievementCategoryCodeType value) {
        this.achievementCategoryCode = value;
    }

    /**
     * Gets the value of the achievementTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAchievementTitle() {
        return achievementTitle;
    }

    /**
     * Sets the value of the achievementTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAchievementTitle(String value) {
        this.achievementTitle = value;
    }

    /**
     * Gets the value of the sponsorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsorName() {
        return sponsorName;
    }

    /**
     * Sets the value of the sponsorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsorName(String value) {
        this.sponsorName = value;
    }

    /**
     * Gets the value of the studentLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link StudentLevelCodeType }
     *     
     */
    public StudentLevelCodeType getStudentLevelCode() {
        return studentLevelCode;
    }

    /**
     * Sets the value of the studentLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentLevelCodeType }
     *     
     */
    public void setStudentLevelCode(StudentLevelCodeType value) {
        this.studentLevelCode = value;
    }

    /**
     * Gets the value of the achievementAwardYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAchievementAwardYear() {
        return achievementAwardYear;
    }

    /**
     * Sets the value of the achievementAwardYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAchievementAwardYear(XMLGregorianCalendar value) {
        this.achievementAwardYear = value;
    }

    /**
     * Gets the value of the achievementAwardYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAchievementAwardYearMonth() {
        return achievementAwardYearMonth;
    }

    /**
     * Sets the value of the achievementAwardYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAchievementAwardYearMonth(XMLGregorianCalendar value) {
        this.achievementAwardYearMonth = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
