//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.StateProvinceCodeType;


/**
 * <p>Java class for OtherCollegeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherCollegeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OtherCollegeName" type="{urn:org:pesc:core:CoreMain:v1.14.0}OtherCollegeNameType" minOccurs="0"/>
 *         &lt;element name="OtherCollegeLocation" type="{urn:org:pesc:core:CoreMain:v1.14.0}OtherCollegeLocationType" minOccurs="0"/>
 *         &lt;element name="OtherCollegeState" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherCollegeType", propOrder = {
    "otherCollegeName",
    "otherCollegeLocation",
    "otherCollegeState"
})
public class OtherCollegeType {

    @XmlElement(name = "OtherCollegeName")
    protected String otherCollegeName;
    @XmlElement(name = "OtherCollegeLocation")
    protected String otherCollegeLocation;
    @XmlElement(name = "OtherCollegeState")
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType otherCollegeState;

    /**
     * Gets the value of the otherCollegeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCollegeName() {
        return otherCollegeName;
    }

    /**
     * Sets the value of the otherCollegeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCollegeName(String value) {
        this.otherCollegeName = value;
    }

    /**
     * Gets the value of the otherCollegeLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCollegeLocation() {
        return otherCollegeLocation;
    }

    /**
     * Sets the value of the otherCollegeLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCollegeLocation(String value) {
        this.otherCollegeLocation = value;
    }

    /**
     * Gets the value of the otherCollegeState property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getOtherCollegeState() {
        return otherCollegeState;
    }

    /**
     * Sets the value of the otherCollegeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setOtherCollegeState(StateProvinceCodeType value) {
        this.otherCollegeState = value;
    }

}
