//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.PassportInformationAvailableCodeType;


/**
 * <p>Java class for PassportDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassportDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PassportInformationAvailableCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}PassportInformationAvailableCodeType" minOccurs="0"/>
 *         &lt;element name="IssuingCountryCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}PassportIssuingCountryCodeType" minOccurs="0"/>
 *         &lt;element name="DocumentExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}PassportExpirationDateType" minOccurs="0"/>
 *         &lt;element name="PassportNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}PassportNumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassportDetailType", propOrder = {
    "passportInformationAvailableCode",
    "issuingCountryCode",
    "documentExpirationDate",
    "passportNumber"
})
public class PassportDetailType {

    @XmlElement(name = "PassportInformationAvailableCode")
    @XmlSchemaType(name = "string")
    protected PassportInformationAvailableCodeType passportInformationAvailableCode;
    @XmlElement(name = "IssuingCountryCode")
    protected String issuingCountryCode;
    @XmlElement(name = "DocumentExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar documentExpirationDate;
    @XmlElement(name = "PassportNumber")
    protected String passportNumber;

    /**
     * Gets the value of the passportInformationAvailableCode property.
     * 
     * @return
     *     possible object is
     *     {@link PassportInformationAvailableCodeType }
     *     
     */
    public PassportInformationAvailableCodeType getPassportInformationAvailableCode() {
        return passportInformationAvailableCode;
    }

    /**
     * Sets the value of the passportInformationAvailableCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportInformationAvailableCodeType }
     *     
     */
    public void setPassportInformationAvailableCode(PassportInformationAvailableCodeType value) {
        this.passportInformationAvailableCode = value;
    }

    /**
     * Gets the value of the issuingCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuingCountryCode() {
        return issuingCountryCode;
    }

    /**
     * Sets the value of the issuingCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuingCountryCode(String value) {
        this.issuingCountryCode = value;
    }

    /**
     * Gets the value of the documentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentExpirationDate() {
        return documentExpirationDate;
    }

    /**
     * Sets the value of the documentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentExpirationDate(XMLGregorianCalendar value) {
        this.documentExpirationDate = value;
    }

    /**
     * Gets the value of the passportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Sets the value of the passportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNumber(String value) {
        this.passportNumber = value;
    }

}
