//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PreviousApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreviousApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SessionDesignator" type="{urn:org:pesc:core:CoreMain:v1.14.0}SessionDesignatorType" minOccurs="0"/>
 *         &lt;element name="CampusName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CampusNameType" minOccurs="0"/>
 *         &lt;element name="AcademicProgramName" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicProgramNameType" minOccurs="0"/>
 *         &lt;element name="SchoolAssignedPersonID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreviousApplicationType", propOrder = {
    "sessionDesignator",
    "campusName",
    "academicProgramName",
    "schoolAssignedPersonID"
})
public class PreviousApplicationType {

    @XmlElement(name = "SessionDesignator")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar sessionDesignator;
    @XmlElement(name = "CampusName")
    protected String campusName;
    @XmlElement(name = "AcademicProgramName")
    protected String academicProgramName;
    @XmlElement(name = "SchoolAssignedPersonID")
    protected Object schoolAssignedPersonID;

    /**
     * Gets the value of the sessionDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSessionDesignator() {
        return sessionDesignator;
    }

    /**
     * Sets the value of the sessionDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSessionDesignator(XMLGregorianCalendar value) {
        this.sessionDesignator = value;
    }

    /**
     * Gets the value of the campusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampusName() {
        return campusName;
    }

    /**
     * Sets the value of the campusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampusName(String value) {
        this.campusName = value;
    }

    /**
     * Gets the value of the academicProgramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcademicProgramName() {
        return academicProgramName;
    }

    /**
     * Sets the value of the academicProgramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcademicProgramName(String value) {
        this.academicProgramName = value;
    }

    /**
     * Gets the value of the schoolAssignedPersonID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSchoolAssignedPersonID() {
        return schoolAssignedPersonID;
    }

    /**
     * Sets the value of the schoolAssignedPersonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSchoolAssignedPersonID(Object value) {
        this.schoolAssignedPersonID = value;
    }

}
