//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.HomesteadExemptionClaimedCodeType;
import org.pesc.core.coremain.v1_14.StateProvinceCodeType;


/**
 * <p>Java class for PropertyOwnedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyOwnedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyPurchaseDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}PropertyPurchaseDateType" minOccurs="0"/>
 *         &lt;element name="PropertyState" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType" minOccurs="0"/>
 *         &lt;element name="PropertyCounty" type="{urn:org:pesc:core:CoreMain:v1.14.0}CountyType" minOccurs="0"/>
 *         &lt;element name="HomesteadExemptionClaimedCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}HomesteadExemptionClaimedCodeType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyOwnedType", propOrder = {
    "propertyPurchaseDate",
    "propertyState",
    "propertyCounty",
    "homesteadExemptionClaimedCode",
    "noteMessage"
})
public class PropertyOwnedType {

    @XmlElement(name = "PropertyPurchaseDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar propertyPurchaseDate;
    @XmlElement(name = "PropertyState")
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType propertyState;
    @XmlElement(name = "PropertyCounty")
    protected String propertyCounty;
    @XmlElement(name = "HomesteadExemptionClaimedCode")
    @XmlSchemaType(name = "string")
    protected HomesteadExemptionClaimedCodeType homesteadExemptionClaimedCode;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the propertyPurchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPropertyPurchaseDate() {
        return propertyPurchaseDate;
    }

    /**
     * Sets the value of the propertyPurchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPropertyPurchaseDate(XMLGregorianCalendar value) {
        this.propertyPurchaseDate = value;
    }

    /**
     * Gets the value of the propertyState property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getPropertyState() {
        return propertyState;
    }

    /**
     * Sets the value of the propertyState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setPropertyState(StateProvinceCodeType value) {
        this.propertyState = value;
    }

    /**
     * Gets the value of the propertyCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCounty() {
        return propertyCounty;
    }

    /**
     * Sets the value of the propertyCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCounty(String value) {
        this.propertyCounty = value;
    }

    /**
     * Gets the value of the homesteadExemptionClaimedCode property.
     * 
     * @return
     *     possible object is
     *     {@link HomesteadExemptionClaimedCodeType }
     *     
     */
    public HomesteadExemptionClaimedCodeType getHomesteadExemptionClaimedCode() {
        return homesteadExemptionClaimedCode;
    }

    /**
     * Sets the value of the homesteadExemptionClaimedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HomesteadExemptionClaimedCodeType }
     *     
     */
    public void setHomesteadExemptionClaimedCode(HomesteadExemptionClaimedCodeType value) {
        this.homesteadExemptionClaimedCode = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
