//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ResidencyEmploymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResidencyEmploymentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FullTimeFlag" type="{urn:org:pesc:core:CoreMain:v1.14.0}FullTimeFlagType" minOccurs="0"/>
 *         &lt;element name="EmploymentBeginDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}EmploymentBeginDateType" minOccurs="0"/>
 *         &lt;element name="EmploymentEndDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}EmploymentEndDateType" minOccurs="0"/>
 *         &lt;element name="EmployerName" type="{urn:org:pesc:core:CoreMain:v1.14.0}EmployerNameType" minOccurs="0"/>
 *         &lt;element name="EmploymentLocation" type="{urn:org:pesc:core:CoreMain:v1.14.0}EmploymentLocationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResidencyEmploymentType", propOrder = {
    "fullTimeFlag",
    "employmentBeginDate",
    "employmentEndDate",
    "employerName",
    "employmentLocation"
})
public class ResidencyEmploymentType {

    @XmlElement(name = "FullTimeFlag")
    protected Boolean fullTimeFlag;
    @XmlElement(name = "EmploymentBeginDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar employmentBeginDate;
    @XmlElement(name = "EmploymentEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar employmentEndDate;
    @XmlElement(name = "EmployerName")
    protected String employerName;
    @XmlElement(name = "EmploymentLocation")
    protected String employmentLocation;

    /**
     * Gets the value of the fullTimeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFullTimeFlag() {
        return fullTimeFlag;
    }

    /**
     * Sets the value of the fullTimeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFullTimeFlag(Boolean value) {
        this.fullTimeFlag = value;
    }

    /**
     * Gets the value of the employmentBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEmploymentBeginDate() {
        return employmentBeginDate;
    }

    /**
     * Sets the value of the employmentBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEmploymentBeginDate(XMLGregorianCalendar value) {
        this.employmentBeginDate = value;
    }

    /**
     * Gets the value of the employmentEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEmploymentEndDate() {
        return employmentEndDate;
    }

    /**
     * Sets the value of the employmentEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEmploymentEndDate(XMLGregorianCalendar value) {
        this.employmentEndDate = value;
    }

    /**
     * Gets the value of the employerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerName() {
        return employerName;
    }

    /**
     * Sets the value of the employerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerName(String value) {
        this.employerName = value;
    }

    /**
     * Gets the value of the employmentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentLocation() {
        return employmentLocation;
    }

    /**
     * Sets the value of the employmentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentLocation(String value) {
        this.employmentLocation = value;
    }

}
