//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.StateProvinceCodeType;


/**
 * <p>Java class for StateIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StateProvinceCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType"/>
 *         &lt;element name="StateIdentificationNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}DriversLicenseNumberType" minOccurs="0"/>
 *         &lt;element name="FirstIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}FirstIssueDateType" minOccurs="0"/>
 *         &lt;element name="LastIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}LastIssueDateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateIdentificationType", propOrder = {
    "stateProvinceCode",
    "stateIdentificationNumber",
    "firstIssueDate",
    "lastIssueDate"
})
public class StateIdentificationType {

    @XmlElement(name = "StateProvinceCode", required = true)
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType stateProvinceCode;
    @XmlElement(name = "StateIdentificationNumber")
    protected String stateIdentificationNumber;
    @XmlElement(name = "FirstIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstIssueDate;
    @XmlElement(name = "LastIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastIssueDate;

    /**
     * Gets the value of the stateProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getStateProvinceCode() {
        return stateProvinceCode;
    }

    /**
     * Sets the value of the stateProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setStateProvinceCode(StateProvinceCodeType value) {
        this.stateProvinceCode = value;
    }

    /**
     * Gets the value of the stateIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateIdentificationNumber() {
        return stateIdentificationNumber;
    }

    /**
     * Sets the value of the stateIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateIdentificationNumber(String value) {
        this.stateIdentificationNumber = value;
    }

    /**
     * Gets the value of the firstIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstIssueDate() {
        return firstIssueDate;
    }

    /**
     * Sets the value of the firstIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstIssueDate(XMLGregorianCalendar value) {
        this.firstIssueDate = value;
    }

    /**
     * Gets the value of the lastIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastIssueDate() {
        return lastIssueDate;
    }

    /**
     * Sets the value of the lastIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastIssueDate(XMLGregorianCalendar value) {
        this.lastIssueDate = value;
    }

}
