//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.EducationTestCodeType;
import org.pesc.core.coremain.v1_14.StudentLevelType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * Tests Type
 * 
 * <p>Java class for TestsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationTestCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}EducationTestCodeType" minOccurs="0"/>
 *         &lt;element name="TestName" type="{urn:org:pesc:core:CoreMain:v1.14.0}TestNameType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="TestDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}TestDateType"/>
 *           &lt;element name="TestYearMonth" type="{urn:org:pesc:core:CoreMain:v1.14.0}TestYearMonthType"/>
 *           &lt;element name="TestYear" type="{urn:org:pesc:core:CoreMain:v1.14.0}TestYearType"/>
 *         &lt;/choice>
 *         &lt;element name="StudentLevel" type="{urn:org:pesc:core:CoreMain:v1.14.0}StudentLevelType" minOccurs="0"/>
 *         &lt;element name="EducationSubtest" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}EducationSubtestType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ScoreValue" type="{urn:org:pesc:core:CoreMain:v1.14.0}ScoreValueType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestsType", propOrder = {
    "educationTestCode",
    "testName",
    "testDate",
    "testYearMonth",
    "testYear",
    "studentLevel",
    "educationSubtest",
    "scoreValue",
    "userDefinedExtensions",
    "noteMessage"
})
public class TestsType {

    @XmlElement(name = "EducationTestCode")
    @XmlSchemaType(name = "string")
    protected EducationTestCodeType educationTestCode;
    @XmlElement(name = "TestName")
    protected String testName;
    @XmlElement(name = "TestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar testDate;
    @XmlElement(name = "TestYearMonth")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar testYearMonth;
    @XmlElement(name = "TestYear")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar testYear;
    @XmlElement(name = "StudentLevel")
    protected StudentLevelType studentLevel;
    @XmlElement(name = "EducationSubtest")
    protected List<EducationSubtestType> educationSubtest;
    @XmlElement(name = "ScoreValue")
    protected String scoreValue;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the educationTestCode property.
     * 
     * @return
     *     possible object is
     *     {@link EducationTestCodeType }
     *     
     */
    public EducationTestCodeType getEducationTestCode() {
        return educationTestCode;
    }

    /**
     * Sets the value of the educationTestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationTestCodeType }
     *     
     */
    public void setEducationTestCode(EducationTestCodeType value) {
        this.educationTestCode = value;
    }

    /**
     * Gets the value of the testName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestName() {
        return testName;
    }

    /**
     * Sets the value of the testName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestName(String value) {
        this.testName = value;
    }

    /**
     * Gets the value of the testDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestDate() {
        return testDate;
    }

    /**
     * Sets the value of the testDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestDate(XMLGregorianCalendar value) {
        this.testDate = value;
    }

    /**
     * Gets the value of the testYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestYearMonth() {
        return testYearMonth;
    }

    /**
     * Sets the value of the testYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestYearMonth(XMLGregorianCalendar value) {
        this.testYearMonth = value;
    }

    /**
     * Gets the value of the testYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestYear() {
        return testYear;
    }

    /**
     * Sets the value of the testYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestYear(XMLGregorianCalendar value) {
        this.testYear = value;
    }

    /**
     * Gets the value of the studentLevel property.
     * 
     * @return
     *     possible object is
     *     {@link StudentLevelType }
     *     
     */
    public StudentLevelType getStudentLevel() {
        return studentLevel;
    }

    /**
     * Sets the value of the studentLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentLevelType }
     *     
     */
    public void setStudentLevel(StudentLevelType value) {
        this.studentLevel = value;
    }

    /**
     * Gets the value of the educationSubtest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the educationSubtest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEducationSubtest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EducationSubtestType }
     * 
     * 
     */
    public List<EducationSubtestType> getEducationSubtest() {
        if (educationSubtest == null) {
            educationSubtest = new ArrayList<EducationSubtestType>();
        }
        return this.educationSubtest;
    }

    /**
     * Gets the value of the scoreValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreValue() {
        return scoreValue;
    }

    /**
     * Sets the value of the scoreValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreValue(String value) {
        this.scoreValue = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
