//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.DocumentOfficialCodeType;
import org.pesc.core.coremain.v1_14.DocumentProcessCodeType;
import org.pesc.core.coremain.v1_14.DocumentTypeCodeType;
import org.pesc.core.coremain.v1_14.TransmissionTypeType;


/**
 * <p>Java class for TransmissionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmissionDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentID" type="{urn:org:pesc:core:CoreMain:v1.14.0}DocumentIDType"/>
 *         &lt;element name="CreatedDateTime" type="{urn:org:pesc:core:CoreMain:v1.14.0}CreatedDateTimeType"/>
 *         &lt;element name="DocumentTypeCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DocumentTypeCodeType"/>
 *         &lt;element name="TransmissionType" type="{urn:org:pesc:core:CoreMain:v1.14.0}TransmissionTypeType"/>
 *         &lt;element name="Source" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}SourceDestinationType"/>
 *         &lt;element name="Destination" type="{urn:org:pesc:sector:AdmissionsRecord:v1.3.0}SourceDestinationType"/>
 *         &lt;element name="DocumentProcessCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DocumentProcessCodeType" minOccurs="0"/>
 *         &lt;element name="DocumentOfficialCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DocumentOfficialCodeType" minOccurs="0"/>
 *         &lt;element name="DocumentCompleteCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}DocumentCompleteCodeType" minOccurs="0"/>
 *         &lt;element name="RequestTrackingID" type="{urn:org:pesc:core:CoreMain:v1.14.0}RequestTrackingIDType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmissionDataType", propOrder = {
    "documentID",
    "createdDateTime",
    "documentTypeCode",
    "transmissionType",
    "source",
    "destination",
    "documentProcessCode",
    "documentOfficialCode",
    "documentCompleteCode",
    "requestTrackingID",
    "noteMessage"
})
public class TransmissionDataType {

    @XmlElement(name = "DocumentID", required = true)
    protected String documentID;
    @XmlElement(name = "CreatedDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    @XmlElement(name = "DocumentTypeCode", required = true)
    @XmlSchemaType(name = "string")
    protected DocumentTypeCodeType documentTypeCode;
    @XmlElement(name = "TransmissionType", required = true)
    @XmlSchemaType(name = "string")
    protected TransmissionTypeType transmissionType;
    @XmlElement(name = "Source", required = true)
    protected SourceDestinationType source;
    @XmlElement(name = "Destination", required = true)
    protected SourceDestinationType destination;
    @XmlElement(name = "DocumentProcessCode")
    @XmlSchemaType(name = "string")
    protected DocumentProcessCodeType documentProcessCode;
    @XmlElement(name = "DocumentOfficialCode")
    @XmlSchemaType(name = "string")
    protected DocumentOfficialCodeType documentOfficialCode;
    @XmlElement(name = "DocumentCompleteCode")
    protected String documentCompleteCode;
    @XmlElement(name = "RequestTrackingID")
    protected String requestTrackingID;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the documentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentTypeCodeType }
     *     
     */
    public DocumentTypeCodeType getDocumentTypeCode() {
        return documentTypeCode;
    }

    /**
     * Sets the value of the documentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentTypeCodeType }
     *     
     */
    public void setDocumentTypeCode(DocumentTypeCodeType value) {
        this.documentTypeCode = value;
    }

    /**
     * Gets the value of the transmissionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionTypeType }
     *     
     */
    public TransmissionTypeType getTransmissionType() {
        return transmissionType;
    }

    /**
     * Sets the value of the transmissionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionTypeType }
     *     
     */
    public void setTransmissionType(TransmissionTypeType value) {
        this.transmissionType = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDestinationType }
     *     
     */
    public SourceDestinationType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDestinationType }
     *     
     */
    public void setSource(SourceDestinationType value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDestinationType }
     *     
     */
    public SourceDestinationType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDestinationType }
     *     
     */
    public void setDestination(SourceDestinationType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the documentProcessCode property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentProcessCodeType }
     *     
     */
    public DocumentProcessCodeType getDocumentProcessCode() {
        return documentProcessCode;
    }

    /**
     * Sets the value of the documentProcessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentProcessCodeType }
     *     
     */
    public void setDocumentProcessCode(DocumentProcessCodeType value) {
        this.documentProcessCode = value;
    }

    /**
     * Gets the value of the documentOfficialCode property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentOfficialCodeType }
     *     
     */
    public DocumentOfficialCodeType getDocumentOfficialCode() {
        return documentOfficialCode;
    }

    /**
     * Sets the value of the documentOfficialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentOfficialCodeType }
     *     
     */
    public void setDocumentOfficialCode(DocumentOfficialCodeType value) {
        this.documentOfficialCode = value;
    }

    /**
     * Gets the value of the documentCompleteCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCompleteCode() {
        return documentCompleteCode;
    }

    /**
     * Sets the value of the documentCompleteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCompleteCode(String value) {
        this.documentCompleteCode = value;
    }

    /**
     * Gets the value of the requestTrackingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestTrackingID() {
        return requestTrackingID;
    }

    /**
     * Sets the value of the requestTrackingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestTrackingID(String value) {
        this.requestTrackingID = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
