//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.VisaReasonForUSBornCodeType;


/**
 * <p>Java class for VisaDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisaDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisaIssuingPostCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}VisaIssuingPostCodeType" minOccurs="0"/>
 *         &lt;element name="NonImmigrantVisaNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}NonImmigrantVisaNumberType" minOccurs="0"/>
 *         &lt;element name="NonImmigrantVisaType" type="{urn:org:pesc:core:CoreMain:v1.14.0}NonImmigrantVisaType" minOccurs="0"/>
 *         &lt;element name="NonImmigrantVisaIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}NonImmigrationVisaIssueDateType" minOccurs="0"/>
 *         &lt;element name="VisaExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}VisaExpirationDateType" minOccurs="0"/>
 *         &lt;element name="VisaReasonForUSBornCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}VisaReasonForUSBornCodeType" minOccurs="0"/>
 *         &lt;element name="VisaControlNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}VisaControlNumberType" minOccurs="0"/>
 *         &lt;element name="NonImmigrantVisaAppliedFor" type="{urn:org:pesc:core:CoreMain:v1.14.0}NonImmigrantVisaType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisaDetailType", propOrder = {
    "visaIssuingPostCode",
    "nonImmigrantVisaNumber",
    "nonImmigrantVisaType",
    "nonImmigrantVisaIssueDate",
    "visaExpirationDate",
    "visaReasonForUSBornCode",
    "visaControlNumber",
    "nonImmigrantVisaAppliedFor"
})
public class VisaDetailType {

    @XmlElement(name = "VisaIssuingPostCode")
    protected String visaIssuingPostCode;
    @XmlElement(name = "NonImmigrantVisaNumber")
    protected String nonImmigrantVisaNumber;
    @XmlElement(name = "NonImmigrantVisaType")
    protected String nonImmigrantVisaType;
    @XmlElement(name = "NonImmigrantVisaIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nonImmigrantVisaIssueDate;
    @XmlElement(name = "VisaExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visaExpirationDate;
    @XmlElement(name = "VisaReasonForUSBornCode")
    @XmlSchemaType(name = "string")
    protected VisaReasonForUSBornCodeType visaReasonForUSBornCode;
    @XmlElement(name = "VisaControlNumber")
    protected String visaControlNumber;
    @XmlElement(name = "NonImmigrantVisaAppliedFor")
    protected String nonImmigrantVisaAppliedFor;

    /**
     * Gets the value of the visaIssuingPostCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaIssuingPostCode() {
        return visaIssuingPostCode;
    }

    /**
     * Sets the value of the visaIssuingPostCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaIssuingPostCode(String value) {
        this.visaIssuingPostCode = value;
    }

    /**
     * Gets the value of the nonImmigrantVisaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonImmigrantVisaNumber() {
        return nonImmigrantVisaNumber;
    }

    /**
     * Sets the value of the nonImmigrantVisaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonImmigrantVisaNumber(String value) {
        this.nonImmigrantVisaNumber = value;
    }

    /**
     * Gets the value of the nonImmigrantVisaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonImmigrantVisaType() {
        return nonImmigrantVisaType;
    }

    /**
     * Sets the value of the nonImmigrantVisaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonImmigrantVisaType(String value) {
        this.nonImmigrantVisaType = value;
    }

    /**
     * Gets the value of the nonImmigrantVisaIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNonImmigrantVisaIssueDate() {
        return nonImmigrantVisaIssueDate;
    }

    /**
     * Sets the value of the nonImmigrantVisaIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNonImmigrantVisaIssueDate(XMLGregorianCalendar value) {
        this.nonImmigrantVisaIssueDate = value;
    }

    /**
     * Gets the value of the visaExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVisaExpirationDate() {
        return visaExpirationDate;
    }

    /**
     * Sets the value of the visaExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVisaExpirationDate(XMLGregorianCalendar value) {
        this.visaExpirationDate = value;
    }

    /**
     * Gets the value of the visaReasonForUSBornCode property.
     * 
     * @return
     *     possible object is
     *     {@link VisaReasonForUSBornCodeType }
     *     
     */
    public VisaReasonForUSBornCodeType getVisaReasonForUSBornCode() {
        return visaReasonForUSBornCode;
    }

    /**
     * Sets the value of the visaReasonForUSBornCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisaReasonForUSBornCodeType }
     *     
     */
    public void setVisaReasonForUSBornCode(VisaReasonForUSBornCodeType value) {
        this.visaReasonForUSBornCode = value;
    }

    /**
     * Gets the value of the visaControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaControlNumber() {
        return visaControlNumber;
    }

    /**
     * Sets the value of the visaControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaControlNumber(String value) {
        this.visaControlNumber = value;
    }

    /**
     * Gets the value of the nonImmigrantVisaAppliedFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonImmigrantVisaAppliedFor() {
        return nonImmigrantVisaAppliedFor;
    }

    /**
     * Sets the value of the nonImmigrantVisaAppliedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonImmigrantVisaAppliedFor(String value) {
        this.nonImmigrantVisaAppliedFor = value;
    }

}
