//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.sector.admissionsrecord.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.StateProvinceCodeType;


/**
 * <p>Java class for VoterRegistrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoterRegistrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StateProvinceCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType"/>
 *         &lt;element name="County" type="{urn:org:pesc:core:CoreMain:v1.14.0}CountyType" minOccurs="0"/>
 *         &lt;element name="VoterRegistrationDistrict" type="{urn:org:pesc:core:CoreMain:v1.14.0}VoterRegistrationDistrictType" minOccurs="0"/>
 *         &lt;element name="City" type="{urn:org:pesc:core:CoreMain:v1.14.0}CityType" minOccurs="0"/>
 *         &lt;element name="VoterRegistrationNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}VoterRegistrationNumberType" minOccurs="0"/>
 *         &lt;element name="FirstIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}FirstIssueDateType" minOccurs="0"/>
 *         &lt;element name="LastIssueDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}LastIssueDateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoterRegistrationType", propOrder = {
    "stateProvinceCode",
    "county",
    "voterRegistrationDistrict",
    "city",
    "voterRegistrationNumber",
    "firstIssueDate",
    "lastIssueDate"
})
public class VoterRegistrationType {

    @XmlElement(name = "StateProvinceCode", required = true)
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType stateProvinceCode;
    @XmlElement(name = "County")
    protected String county;
    @XmlElement(name = "VoterRegistrationDistrict")
    protected String voterRegistrationDistrict;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "VoterRegistrationNumber")
    protected String voterRegistrationNumber;
    @XmlElement(name = "FirstIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstIssueDate;
    @XmlElement(name = "LastIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastIssueDate;

    /**
     * Gets the value of the stateProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getStateProvinceCode() {
        return stateProvinceCode;
    }

    /**
     * Sets the value of the stateProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setStateProvinceCode(StateProvinceCodeType value) {
        this.stateProvinceCode = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the voterRegistrationDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoterRegistrationDistrict() {
        return voterRegistrationDistrict;
    }

    /**
     * Sets the value of the voterRegistrationDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoterRegistrationDistrict(String value) {
        this.voterRegistrationDistrict = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the voterRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoterRegistrationNumber() {
        return voterRegistrationNumber;
    }

    /**
     * Sets the value of the voterRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoterRegistrationNumber(String value) {
        this.voterRegistrationNumber = value;
    }

    /**
     * Gets the value of the firstIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstIssueDate() {
        return firstIssueDate;
    }

    /**
     * Sets the value of the firstIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstIssueDate(XMLGregorianCalendar value) {
        this.firstIssueDate = value;
    }

    /**
     * Gets the value of the lastIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastIssueDate() {
        return lastIssueDate;
    }

    /**
     * Sets the value of the lastIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastIssueDate(XMLGregorianCalendar value) {
        this.lastIssueDate = value;
    }

}
