//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:12 PM PST 
//


package org.pesc.message.academicrecordbatch.v2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.AcademicRecordBatchType;
import org.pesc.sector.academicrecord.v1_9.TransmissionBatchType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchEnvelope" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}TransmissionBatchType" minOccurs="0"/>
 *         &lt;element name="BatchContent" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicRecordBatchType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchEnvelope",
    "batchContent"
})
@XmlRootElement(name = "AcademicRecordBatch")
public class AcademicRecordBatch {

    @XmlElement(name = "BatchEnvelope")
    protected TransmissionBatchType batchEnvelope;
    @XmlElement(name = "BatchContent", required = true)
    protected AcademicRecordBatchType batchContent;

    /**
     * Gets the value of the batchEnvelope property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionBatchType }
     *     
     */
    public TransmissionBatchType getBatchEnvelope() {
        return batchEnvelope;
    }

    /**
     * Sets the value of the batchEnvelope property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionBatchType }
     *     
     */
    public void setBatchEnvelope(TransmissionBatchType value) {
        this.batchEnvelope = value;
    }

    /**
     * Gets the value of the batchContent property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicRecordBatchType }
     *     
     */
    public AcademicRecordBatchType getBatchContent() {
        return batchContent;
    }

    /**
     * Sets the value of the batchContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicRecordBatchType }
     *     
     */
    public void setBatchContent(AcademicRecordBatchType value) {
        this.batchContent = value;
    }

}
