//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:org:pesc:core:CoreMain:v1.14.0}GeneralAddressGroup"/>
 *         &lt;element name="EffectiveDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AddressEffectiveDateType" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AddressExpirationDateType" minOccurs="0"/>
 *         &lt;element name="AttentionLine" type="{urn:org:pesc:core:CoreMain:v1.14.0}AttentionLineType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "content"
})
public class AddressType {

    @XmlElementRefs({
        @XmlElementRef(name = "EffectiveDate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StateProvince", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AddressLine", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "City", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AttentionLine", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CountryCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StateProvinceCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PostalCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ExpirationDate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NoteMessage", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "PostalCode" is used by two different parts of a schema. See: 
     * line 4344 of file:/opte/pesccoltrnjar/src/ca/bccampus/esb/dtos/v140/schemas/CoreMain_v1.14.0.xsd
     * line 4335 of file:/opte/pesccoltrnjar/src/ca/bccampus/esb/dtos/v140/schemas/CoreMain_v1.14.0.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link StateProvinceCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
