//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttendedSchoolResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttendedSchoolResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseSummary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TotalCount" type="{urn:org:pesc:core:CoreMain:v1.14.0}TotalCountType"/>
 *                   &lt;element name="TotalNumberAwards" type="{urn:org:pesc:core:CoreMain:v1.14.0}TotalCountType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttendedSchoolResponseType", propOrder = {
    "responseSummary"
})
@XmlSeeAlso({
    AttendedSchoolDisbursementResponseType.class
})
public class AttendedSchoolResponseType {

    @XmlElement(name = "ResponseSummary", required = true)
    protected AttendedSchoolResponseType.ResponseSummary responseSummary;

    /**
     * Gets the value of the responseSummary property.
     * 
     * @return
     *     possible object is
     *     {@link AttendedSchoolResponseType.ResponseSummary }
     *     
     */
    public AttendedSchoolResponseType.ResponseSummary getResponseSummary() {
        return responseSummary;
    }

    /**
     * Sets the value of the responseSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttendedSchoolResponseType.ResponseSummary }
     *     
     */
    public void setResponseSummary(AttendedSchoolResponseType.ResponseSummary value) {
        this.responseSummary = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TotalCount" type="{urn:org:pesc:core:CoreMain:v1.14.0}TotalCountType"/>
     *         &lt;element name="TotalNumberAwards" type="{urn:org:pesc:core:CoreMain:v1.14.0}TotalCountType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalCount",
        "totalNumberAwards"
    })
    public static class ResponseSummary {

        @XmlElement(name = "TotalCount")
        @XmlSchemaType(name = "integer")
        protected int totalCount;
        @XmlElement(name = "TotalNumberAwards")
        @XmlSchemaType(name = "integer")
        protected int totalNumberAwards;

        /**
         * Gets the value of the totalCount property.
         * 
         */
        public int getTotalCount() {
            return totalCount;
        }

        /**
         * Sets the value of the totalCount property.
         * 
         */
        public void setTotalCount(int value) {
            this.totalCount = value;
        }

        /**
         * Gets the value of the totalNumberAwards property.
         * 
         */
        public int getTotalNumberAwards() {
            return totalNumberAwards;
        }

        /**
         * Sets the value of the totalNumberAwards property.
         * 
         */
        public void setTotalNumberAwards(int value) {
            this.totalNumberAwards = value;
        }

    }

}
