//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AttendanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttendanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttendanceStatusCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}AttendanceStatusCodeType" minOccurs="0"/>
 *         &lt;element name="AttendanceStatusCodeBeginDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AttendanceStatusCodeBeginDateType" minOccurs="0"/>
 *         &lt;element name="AttendanceStatusCodeEndDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}AttendanceStatusCodeEndDateType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttendanceType", propOrder = {
    "attendanceStatusCode",
    "attendanceStatusCodeBeginDate",
    "attendanceStatusCodeEndDate",
    "noteMessage"
})
public class AttendanceType {

    @XmlElement(name = "AttendanceStatusCode")
    @XmlSchemaType(name = "string")
    protected AttendanceStatusCodeType attendanceStatusCode;
    @XmlElement(name = "AttendanceStatusCodeBeginDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar attendanceStatusCodeBeginDate;
    @XmlElement(name = "AttendanceStatusCodeEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar attendanceStatusCodeEndDate;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the attendanceStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link AttendanceStatusCodeType }
     *     
     */
    public AttendanceStatusCodeType getAttendanceStatusCode() {
        return attendanceStatusCode;
    }

    /**
     * Sets the value of the attendanceStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttendanceStatusCodeType }
     *     
     */
    public void setAttendanceStatusCode(AttendanceStatusCodeType value) {
        this.attendanceStatusCode = value;
    }

    /**
     * Gets the value of the attendanceStatusCodeBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttendanceStatusCodeBeginDate() {
        return attendanceStatusCodeBeginDate;
    }

    /**
     * Sets the value of the attendanceStatusCodeBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttendanceStatusCodeBeginDate(XMLGregorianCalendar value) {
        this.attendanceStatusCodeBeginDate = value;
    }

    /**
     * Gets the value of the attendanceStatusCodeEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttendanceStatusCodeEndDate() {
        return attendanceStatusCodeEndDate;
    }

    /**
     * Sets the value of the attendanceStatusCodeEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttendanceStatusCodeEndDate(XMLGregorianCalendar value) {
        this.attendanceStatusCodeEndDate = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
