//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttendedCollegeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttendedCollegeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EitherParent"/>
 *     &lt;enumeration value="GrandParent"/>
 *     &lt;enumeration value="Siblings"/>
 *     &lt;enumeration value="Spouse"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttendedCollegeCodeType")
@XmlEnum
public enum AttendedCollegeCodeType {

    @XmlEnumValue("EitherParent")
    EITHER_PARENT("EitherParent"),
    @XmlEnumValue("GrandParent")
    GRAND_PARENT("GrandParent"),
    @XmlEnumValue("Siblings")
    SIBLINGS("Siblings"),
    @XmlEnumValue("Spouse")
    SPOUSE("Spouse");
    private final String value;

    AttendedCollegeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttendedCollegeCodeType fromValue(String v) {
        for (AttendedCollegeCodeType c: AttendedCollegeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
