//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourseLevelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CourseLevelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Accelerated"/>
 *     &lt;enumeration value="AdultBasic"/>
 *     &lt;enumeration value="AdvancedPlacement"/>
 *     &lt;enumeration value="Basic"/>
 *     &lt;enumeration value="CollegeLevel"/>
 *     &lt;enumeration value="CollegePreparatory"/>
 *     &lt;enumeration value="Dual"/>
 *     &lt;enumeration value="Dual Grad/Upper"/>
 *     &lt;enumeration value="Dual HS/Undergrad"/>
 *     &lt;enumeration value="GiftedTalented"/>
 *     &lt;enumeration value="GraduateProfessional"/>
 *     &lt;enumeration value="Honors"/>
 *     &lt;enumeration value="InternationalBaccalaureate"/>
 *     &lt;enumeration value="LowerDivision"/>
 *     &lt;enumeration value="NonAcademic"/>
 *     &lt;enumeration value="Regents"/>
 *     &lt;enumeration value="Remedial"/>
 *     &lt;enumeration value="SpecialEducation"/>
 *     &lt;enumeration value="TechnicalPreparatory"/>
 *     &lt;enumeration value="UpperDivision"/>
 *     &lt;enumeration value="Vocational"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CourseLevelType")
@XmlEnum
public enum CourseLevelType {

    @XmlEnumValue("Accelerated")
    ACCELERATED("Accelerated"),
    @XmlEnumValue("AdultBasic")
    ADULT_BASIC("AdultBasic"),
    @XmlEnumValue("AdvancedPlacement")
    ADVANCED_PLACEMENT("AdvancedPlacement"),
    @XmlEnumValue("Basic")
    BASIC("Basic"),
    @XmlEnumValue("CollegeLevel")
    COLLEGE_LEVEL("CollegeLevel"),
    @XmlEnumValue("CollegePreparatory")
    COLLEGE_PREPARATORY("CollegePreparatory"),
    @XmlEnumValue("Dual")
    DUAL("Dual"),
    @XmlEnumValue("Dual Grad/Upper")
    DUAL_GRAD_UPPER("Dual Grad/Upper"),
    @XmlEnumValue("Dual HS/Undergrad")
    DUAL_HS_UNDERGRAD("Dual HS/Undergrad"),
    @XmlEnumValue("GiftedTalented")
    GIFTED_TALENTED("GiftedTalented"),
    @XmlEnumValue("GraduateProfessional")
    GRADUATE_PROFESSIONAL("GraduateProfessional"),
    @XmlEnumValue("Honors")
    HONORS("Honors"),
    @XmlEnumValue("InternationalBaccalaureate")
    INTERNATIONAL_BACCALAUREATE("InternationalBaccalaureate"),
    @XmlEnumValue("LowerDivision")
    LOWER_DIVISION("LowerDivision"),
    @XmlEnumValue("NonAcademic")
    NON_ACADEMIC("NonAcademic"),
    @XmlEnumValue("Regents")
    REGENTS("Regents"),
    @XmlEnumValue("Remedial")
    REMEDIAL("Remedial"),
    @XmlEnumValue("SpecialEducation")
    SPECIAL_EDUCATION("SpecialEducation"),
    @XmlEnumValue("TechnicalPreparatory")
    TECHNICAL_PREPARATORY("TechnicalPreparatory"),
    @XmlEnumValue("UpperDivision")
    UPPER_DIVISION("UpperDivision"),
    @XmlEnumValue("Vocational")
    VOCATIONAL("Vocational");
    private final String value;

    CourseLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CourseLevelType fromValue(String v) {
        for (CourseLevelType c: CourseLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
