//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  Provides Information about person's job status at school in which person is seeking admission
 * 
 * <p>Java class for EmploymentAtAppliedSchoolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmploymentAtAppliedSchoolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RelationshipCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}RelationshipCodeType" minOccurs="0"/>
 *         &lt;element name="CampusName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CampusNameType" minOccurs="0"/>
 *         &lt;element name="EmploymentStatusCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}EmploymentStatusCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmploymentAtAppliedSchoolType", propOrder = {
    "relationshipCode",
    "campusName",
    "employmentStatusCode"
})
public class EmploymentAtAppliedSchoolType {

    @XmlElement(name = "RelationshipCode")
    @XmlSchemaType(name = "string")
    protected RelationshipCodeType relationshipCode;
    @XmlElement(name = "CampusName")
    protected String campusName;
    @XmlElement(name = "EmploymentStatusCode")
    @XmlSchemaType(name = "string")
    protected EmploymentStatusCodeType employmentStatusCode;

    /**
     * Gets the value of the relationshipCode property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipCodeType }
     *     
     */
    public RelationshipCodeType getRelationshipCode() {
        return relationshipCode;
    }

    /**
     * Sets the value of the relationshipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipCodeType }
     *     
     */
    public void setRelationshipCode(RelationshipCodeType value) {
        this.relationshipCode = value;
    }

    /**
     * Gets the value of the campusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampusName() {
        return campusName;
    }

    /**
     * Sets the value of the campusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampusName(String value) {
        this.campusName = value;
    }

    /**
     * Gets the value of the employmentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentStatusCodeType }
     *     
     */
    public EmploymentStatusCodeType getEmploymentStatusCode() {
        return employmentStatusCode;
    }

    /**
     * Sets the value of the employmentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentStatusCodeType }
     *     
     */
    public void setEmploymentStatusCode(EmploymentStatusCodeType value) {
        this.employmentStatusCode = value;
    }

}
