//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:23 PM PST 
//


package org.pesc.core.coremain.v1_14;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LicensureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LicensureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LicensureName" type="{urn:org:pesc:core:CoreMain:v1.14.0}LicensureNameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LicensureStateProvinceCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}StateProvinceCodeType" minOccurs="0"/>
 *         &lt;element name="LicensurePassageDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}LicensurePassageDateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LicensureFulfillmentCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}LicensureFulfillmentCodeType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicensureType", propOrder = {
    "licensureName",
    "licensureStateProvinceCode",
    "licensurePassageDate",
    "licensureFulfillmentCode",
    "noteMessage"
})
public class LicensureType {

    @XmlElement(name = "LicensureName")
    protected List<String> licensureName;
    @XmlElement(name = "LicensureStateProvinceCode")
    @XmlSchemaType(name = "token")
    protected StateProvinceCodeType licensureStateProvinceCode;
    @XmlElement(name = "LicensurePassageDate")
    @XmlSchemaType(name = "date")
    protected List<XMLGregorianCalendar> licensurePassageDate;
    @XmlElement(name = "LicensureFulfillmentCode")
    @XmlSchemaType(name = "string")
    protected LicensureFulfillmentCodeType licensureFulfillmentCode;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the licensureName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licensureName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicensureName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLicensureName() {
        if (licensureName == null) {
            licensureName = new ArrayList<String>();
        }
        return this.licensureName;
    }

    /**
     * Gets the value of the licensureStateProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public StateProvinceCodeType getLicensureStateProvinceCode() {
        return licensureStateProvinceCode;
    }

    /**
     * Sets the value of the licensureStateProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceCodeType }
     *     
     */
    public void setLicensureStateProvinceCode(StateProvinceCodeType value) {
        this.licensureStateProvinceCode = value;
    }

    /**
     * Gets the value of the licensurePassageDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licensurePassageDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicensurePassageDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getLicensurePassageDate() {
        if (licensurePassageDate == null) {
            licensurePassageDate = new ArrayList<XMLGregorianCalendar>();
        }
        return this.licensurePassageDate;
    }

    /**
     * Gets the value of the licensureFulfillmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link LicensureFulfillmentCodeType }
     *     
     */
    public LicensureFulfillmentCodeType getLicensureFulfillmentCode() {
        return licensureFulfillmentCode;
    }

    /**
     * Sets the value of the licensureFulfillmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicensureFulfillmentCodeType }
     *     
     */
    public void setLicensureFulfillmentCode(LicensureFulfillmentCodeType value) {
        this.licensureFulfillmentCode = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
