//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:19 PM PST 
//


package org.pesc.message.transcriptacknowledgement.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.sector.academicrecord.v1_9.AcademicSummaryBaseType;
import org.pesc.sector.academicrecord.v1_9.AcknowledgmentPersonType;
import org.pesc.sector.academicrecord.v1_9.TransmissionDataType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransmissionData" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}TransmissionDataType"/>
 *         &lt;element name="Person" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}AcknowledgmentPersonType"/>
 *         &lt;element name="AcademicSummary" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}AcademicSummaryBaseType" minOccurs="0"/>
 *         &lt;element name="AcademicAwardTotal" type="{urn:org:pesc:core:CoreMain:v1.14.0}AcademicAwardTotalType"/>
 *         &lt;element name="CourseTotal" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseTotalType"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transmissionData",
    "person",
    "academicSummary",
    "academicAwardTotal",
    "courseTotal",
    "noteMessage"
})
@XmlRootElement(name = "Acknowledgment")
public class Acknowledgment {

    @XmlElement(name = "TransmissionData", required = true)
    protected TransmissionDataType transmissionData;
    @XmlElement(name = "Person", required = true)
    protected AcknowledgmentPersonType person;
    @XmlElement(name = "AcademicSummary")
    protected AcademicSummaryBaseType academicSummary;
    @XmlElement(name = "AcademicAwardTotal")
    @XmlSchemaType(name = "integer")
    protected int academicAwardTotal;
    @XmlElement(name = "CourseTotal")
    @XmlSchemaType(name = "integer")
    protected int courseTotal;
    @XmlElement(name = "NoteMessage")
    protected List<String> noteMessage;

    /**
     * Gets the value of the transmissionData property.
     * 
     * @return
     *     possible object is
     *     {@link TransmissionDataType }
     *     
     */
    public TransmissionDataType getTransmissionData() {
        return transmissionData;
    }

    /**
     * Sets the value of the transmissionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmissionDataType }
     *     
     */
    public void setTransmissionData(TransmissionDataType value) {
        this.transmissionData = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link AcknowledgmentPersonType }
     *     
     */
    public AcknowledgmentPersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcknowledgmentPersonType }
     *     
     */
    public void setPerson(AcknowledgmentPersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the academicSummary property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicSummaryBaseType }
     *     
     */
    public AcademicSummaryBaseType getAcademicSummary() {
        return academicSummary;
    }

    /**
     * Sets the value of the academicSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicSummaryBaseType }
     *     
     */
    public void setAcademicSummary(AcademicSummaryBaseType value) {
        this.academicSummary = value;
    }

    /**
     * Gets the value of the academicAwardTotal property.
     * 
     */
    public int getAcademicAwardTotal() {
        return academicAwardTotal;
    }

    /**
     * Sets the value of the academicAwardTotal property.
     * 
     */
    public void setAcademicAwardTotal(int value) {
        this.academicAwardTotal = value;
    }

    /**
     * Gets the value of the courseTotal property.
     * 
     */
    public int getCourseTotal() {
        return courseTotal;
    }

    /**
     * Sets the value of the courseTotal property.
     * 
     */
    public void setCourseTotal(int value) {
        this.courseTotal = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoteMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNoteMessage() {
        if (noteMessage == null) {
            noteMessage = new ArrayList<String>();
        }
        return this.noteMessage;
    }

}
