//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:19 PM PST 
//


package org.pesc.sector.academicrecord.v1_9;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.CorequisiteCourseConditionCodeType;


/**
 * <p>Java class for CourseCorequisiteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseCorequisiteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CorequisiteCourseIndicator" type="{urn:org:pesc:core:CoreMain:v1.14.0}CorequisiteCourseIndicatorType"/>
 *         &lt;element name="CourseSubjectAbbreviation" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseSubjectAbbreviationType"/>
 *         &lt;element name="CourseNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseNumberType"/>
 *         &lt;element name="CorequisiteCourseCondition" type="{urn:org:pesc:core:CoreMain:v1.14.0}CorequisiteCourseConditionCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseCorequisiteType", propOrder = {
    "corequisiteCourseIndicator",
    "courseSubjectAbbreviation",
    "courseNumber",
    "corequisiteCourseCondition"
})
public class CourseCorequisiteType {

    @XmlElement(name = "CorequisiteCourseIndicator")
    protected boolean corequisiteCourseIndicator;
    @XmlElement(name = "CourseSubjectAbbreviation", required = true)
    protected String courseSubjectAbbreviation;
    @XmlElement(name = "CourseNumber", required = true)
    protected String courseNumber;
    @XmlElement(name = "CorequisiteCourseCondition", required = true)
    @XmlSchemaType(name = "string")
    protected CorequisiteCourseConditionCodeType corequisiteCourseCondition;

    /**
     * Gets the value of the corequisiteCourseIndicator property.
     * 
     */
    public boolean isCorequisiteCourseIndicator() {
        return corequisiteCourseIndicator;
    }

    /**
     * Sets the value of the corequisiteCourseIndicator property.
     * 
     */
    public void setCorequisiteCourseIndicator(boolean value) {
        this.corequisiteCourseIndicator = value;
    }

    /**
     * Gets the value of the courseSubjectAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseSubjectAbbreviation() {
        return courseSubjectAbbreviation;
    }

    /**
     * Sets the value of the courseSubjectAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseSubjectAbbreviation(String value) {
        this.courseSubjectAbbreviation = value;
    }

    /**
     * Gets the value of the courseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * Sets the value of the courseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseNumber(String value) {
        this.courseNumber = value;
    }

    /**
     * Gets the value of the corequisiteCourseCondition property.
     * 
     * @return
     *     possible object is
     *     {@link CorequisiteCourseConditionCodeType }
     *     
     */
    public CorequisiteCourseConditionCodeType getCorequisiteCourseCondition() {
        return corequisiteCourseCondition;
    }

    /**
     * Sets the value of the corequisiteCourseCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorequisiteCourseConditionCodeType }
     *     
     */
    public void setCorequisiteCourseCondition(CorequisiteCourseConditionCodeType value) {
        this.corequisiteCourseCondition = value;
    }

}
