//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:19 PM PST 
//


package org.pesc.sector.academicrecord.v1_9;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.pesc.core.coremain.v1_14.CourseCreditBasisType;
import org.pesc.core.coremain.v1_14.CourseHonorsCodeType;
import org.pesc.core.coremain.v1_14.CourseLevelType;
import org.pesc.core.coremain.v1_14.LanguageOfInstructionType;
import org.pesc.core.coremain.v1_14.LicensureType;
import org.pesc.core.coremain.v1_14.RAPType;
import org.pesc.core.coremain.v1_14.UserDefinedExtensionsType;


/**
 * <p>Java class for CourseInventoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourseInventoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseCreditUnits" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCreditUnitsType"/>
 *         &lt;element name="CourseCreditMaximumValue" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCreditMaximumValueType" minOccurs="0"/>
 *         &lt;element name="CourseCreditMinimumValue" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCreditMinimumValueType" minOccurs="0"/>
 *         &lt;element name="CourseAcademicGradeScaleCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseAcademicGradeScaleCodeType" minOccurs="0"/>
 *         &lt;element name="CourseRepeatability" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}CourseRepeatabilityType" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="CourseCIPCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCreditBasisType" minOccurs="0"/>
 *           &lt;element name="CourseCSISCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseCSISCodeType" minOccurs="0"/>
 *           &lt;element name="CourseNCESCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseNCESCodeType" minOccurs="0"/>
 *           &lt;element name="CoursePSISCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CoursePSISCodeType" minOccurs="0"/>
 *           &lt;element name="CourseSCEDCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseSCEDCodeType" minOccurs="0"/>
 *           &lt;element name="CourseUSISCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseUSISCodeType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="CourseLevel" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseLevelType" minOccurs="0"/>
 *         &lt;element name="CourseHonorsCode" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseHonorsCodeType" minOccurs="0"/>
 *         &lt;element name="CourseSubjectAbbreviation" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseSubjectAbbreviationType" minOccurs="0"/>
 *         &lt;element name="CourseLongDepartmentName" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseLongDepartmentNameType" minOccurs="0"/>
 *         &lt;element name="CourseNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:org:pesc:core:CoreMain:v1.14.0}CourseNumberType">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CourseSubID" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseSubNumberType" minOccurs="0"/>
 *         &lt;element name="PreviousCourseID" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}PreviousCourseIDType" minOccurs="0"/>
 *         &lt;element name="RelatedCourseID" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}RelatedCourseIDType" minOccurs="0"/>
 *         &lt;element name="CourseShortTitle" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseTitleType" minOccurs="0"/>
 *         &lt;element name="CourseLongTitle" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseLongTitleType" minOccurs="0"/>
 *         &lt;element name="CourseDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:org:pesc:core:CoreMain:v1.14.0}CourseDescriptionType">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CourseEffectiveDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseEffectiveDateType" minOccurs="0"/>
 *         &lt;element name="CourseExpirationDate" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseExpirationDateType" minOccurs="0"/>
 *         &lt;element name="CoursePrerequisite" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}CoursePrerequisiteType" minOccurs="0"/>
 *         &lt;element name="CourseCoRequisite" type="{urn:org:pesc:sector:AcademicRecord:v1.9.0}CourseCorequisiteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Requirement" type="{urn:org:pesc:core:CoreMain:v1.14.0}RAPType" minOccurs="0"/>
 *         &lt;element name="Licensure" type="{urn:org:pesc:core:CoreMain:v1.14.0}LicensureType" minOccurs="0"/>
 *         &lt;element name="LanguageOfInstruction" type="{urn:org:pesc:core:CoreMain:v1.14.0}LanguageOfInstructionType" minOccurs="0"/>
 *         &lt;element name="NoteMessage" type="{urn:org:pesc:core:CoreMain:v1.14.0}NoteMessageType" minOccurs="0"/>
 *         &lt;element name="UserDefinedExtensions" type="{urn:org:pesc:core:CoreMain:v1.14.0}UserDefinedExtensionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourseInventoryType", propOrder = {
    "courseCreditUnits",
    "courseCreditMaximumValue",
    "courseCreditMinimumValue",
    "courseAcademicGradeScaleCode",
    "courseRepeatability",
    "courseCIPCode",
    "courseCSISCode",
    "courseNCESCode",
    "coursePSISCode",
    "courseSCEDCode",
    "courseUSISCode",
    "courseLevel",
    "courseHonorsCode",
    "courseSubjectAbbreviation",
    "courseLongDepartmentName",
    "courseNumber",
    "courseSubID",
    "previousCourseID",
    "relatedCourseID",
    "courseShortTitle",
    "courseLongTitle",
    "courseDescription",
    "courseEffectiveDate",
    "courseExpirationDate",
    "coursePrerequisite",
    "courseCoRequisite",
    "requirement",
    "licensure",
    "languageOfInstruction",
    "noteMessage",
    "userDefinedExtensions"
})
public class CourseInventoryType {

    @XmlElement(name = "CourseCreditUnits", required = true)
    protected String courseCreditUnits;
    @XmlElement(name = "CourseCreditMaximumValue")
    protected BigDecimal courseCreditMaximumValue;
    @XmlElement(name = "CourseCreditMinimumValue")
    protected BigDecimal courseCreditMinimumValue;
    @XmlElement(name = "CourseAcademicGradeScaleCode")
    protected String courseAcademicGradeScaleCode;
    @XmlElement(name = "CourseRepeatability")
    protected CourseRepeatabilityType courseRepeatability;
    @XmlElement(name = "CourseCIPCode")
    @XmlSchemaType(name = "string")
    protected CourseCreditBasisType courseCIPCode;
    @XmlElement(name = "CourseCSISCode")
    protected String courseCSISCode;
    @XmlElement(name = "CourseNCESCode")
    protected String courseNCESCode;
    @XmlElement(name = "CoursePSISCode")
    protected String coursePSISCode;
    @XmlElement(name = "CourseSCEDCode")
    protected String courseSCEDCode;
    @XmlElement(name = "CourseUSISCode")
    protected String courseUSISCode;
    @XmlElement(name = "CourseLevel")
    @XmlSchemaType(name = "string")
    protected CourseLevelType courseLevel;
    @XmlElement(name = "CourseHonorsCode")
    @XmlSchemaType(name = "string")
    protected CourseHonorsCodeType courseHonorsCode;
    @XmlElement(name = "CourseSubjectAbbreviation")
    protected String courseSubjectAbbreviation;
    @XmlElement(name = "CourseLongDepartmentName")
    protected String courseLongDepartmentName;
    @XmlElement(name = "CourseNumber", required = true)
    protected String courseNumber;
    @XmlElement(name = "CourseSubID")
    protected String courseSubID;
    @XmlElement(name = "PreviousCourseID")
    protected PreviousCourseIDType previousCourseID;
    @XmlElement(name = "RelatedCourseID")
    protected RelatedCourseIDType relatedCourseID;
    @XmlElement(name = "CourseShortTitle")
    protected String courseShortTitle;
    @XmlElement(name = "CourseLongTitle")
    protected String courseLongTitle;
    @XmlElement(name = "CourseDescription")
    protected String courseDescription;
    @XmlElement(name = "CourseEffectiveDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar courseEffectiveDate;
    @XmlElement(name = "CourseExpirationDate")
    protected String courseExpirationDate;
    @XmlElement(name = "CoursePrerequisite")
    protected CoursePrerequisiteType coursePrerequisite;
    @XmlElement(name = "CourseCoRequisite")
    protected List<CourseCorequisiteType> courseCoRequisite;
    @XmlElement(name = "Requirement")
    protected RAPType requirement;
    @XmlElement(name = "Licensure")
    protected LicensureType licensure;
    @XmlElement(name = "LanguageOfInstruction")
    protected LanguageOfInstructionType languageOfInstruction;
    @XmlElement(name = "NoteMessage")
    protected String noteMessage;
    @XmlElement(name = "UserDefinedExtensions")
    protected UserDefinedExtensionsType userDefinedExtensions;

    /**
     * Gets the value of the courseCreditUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseCreditUnits() {
        return courseCreditUnits;
    }

    /**
     * Sets the value of the courseCreditUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseCreditUnits(String value) {
        this.courseCreditUnits = value;
    }

    /**
     * Gets the value of the courseCreditMaximumValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCourseCreditMaximumValue() {
        return courseCreditMaximumValue;
    }

    /**
     * Sets the value of the courseCreditMaximumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCourseCreditMaximumValue(BigDecimal value) {
        this.courseCreditMaximumValue = value;
    }

    /**
     * Gets the value of the courseCreditMinimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCourseCreditMinimumValue() {
        return courseCreditMinimumValue;
    }

    /**
     * Sets the value of the courseCreditMinimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCourseCreditMinimumValue(BigDecimal value) {
        this.courseCreditMinimumValue = value;
    }

    /**
     * Gets the value of the courseAcademicGradeScaleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseAcademicGradeScaleCode() {
        return courseAcademicGradeScaleCode;
    }

    /**
     * Sets the value of the courseAcademicGradeScaleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseAcademicGradeScaleCode(String value) {
        this.courseAcademicGradeScaleCode = value;
    }

    /**
     * Gets the value of the courseRepeatability property.
     * 
     * @return
     *     possible object is
     *     {@link CourseRepeatabilityType }
     *     
     */
    public CourseRepeatabilityType getCourseRepeatability() {
        return courseRepeatability;
    }

    /**
     * Sets the value of the courseRepeatability property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseRepeatabilityType }
     *     
     */
    public void setCourseRepeatability(CourseRepeatabilityType value) {
        this.courseRepeatability = value;
    }

    /**
     * Gets the value of the courseCIPCode property.
     * 
     * @return
     *     possible object is
     *     {@link CourseCreditBasisType }
     *     
     */
    public CourseCreditBasisType getCourseCIPCode() {
        return courseCIPCode;
    }

    /**
     * Sets the value of the courseCIPCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseCreditBasisType }
     *     
     */
    public void setCourseCIPCode(CourseCreditBasisType value) {
        this.courseCIPCode = value;
    }

    /**
     * Gets the value of the courseCSISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseCSISCode() {
        return courseCSISCode;
    }

    /**
     * Sets the value of the courseCSISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseCSISCode(String value) {
        this.courseCSISCode = value;
    }

    /**
     * Gets the value of the courseNCESCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseNCESCode() {
        return courseNCESCode;
    }

    /**
     * Sets the value of the courseNCESCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseNCESCode(String value) {
        this.courseNCESCode = value;
    }

    /**
     * Gets the value of the coursePSISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoursePSISCode() {
        return coursePSISCode;
    }

    /**
     * Sets the value of the coursePSISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoursePSISCode(String value) {
        this.coursePSISCode = value;
    }

    /**
     * Gets the value of the courseSCEDCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseSCEDCode() {
        return courseSCEDCode;
    }

    /**
     * Sets the value of the courseSCEDCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseSCEDCode(String value) {
        this.courseSCEDCode = value;
    }

    /**
     * Gets the value of the courseUSISCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseUSISCode() {
        return courseUSISCode;
    }

    /**
     * Sets the value of the courseUSISCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseUSISCode(String value) {
        this.courseUSISCode = value;
    }

    /**
     * Gets the value of the courseLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CourseLevelType }
     *     
     */
    public CourseLevelType getCourseLevel() {
        return courseLevel;
    }

    /**
     * Sets the value of the courseLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseLevelType }
     *     
     */
    public void setCourseLevel(CourseLevelType value) {
        this.courseLevel = value;
    }

    /**
     * Gets the value of the courseHonorsCode property.
     * 
     * @return
     *     possible object is
     *     {@link CourseHonorsCodeType }
     *     
     */
    public CourseHonorsCodeType getCourseHonorsCode() {
        return courseHonorsCode;
    }

    /**
     * Sets the value of the courseHonorsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseHonorsCodeType }
     *     
     */
    public void setCourseHonorsCode(CourseHonorsCodeType value) {
        this.courseHonorsCode = value;
    }

    /**
     * Gets the value of the courseSubjectAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseSubjectAbbreviation() {
        return courseSubjectAbbreviation;
    }

    /**
     * Sets the value of the courseSubjectAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseSubjectAbbreviation(String value) {
        this.courseSubjectAbbreviation = value;
    }

    /**
     * Gets the value of the courseLongDepartmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseLongDepartmentName() {
        return courseLongDepartmentName;
    }

    /**
     * Sets the value of the courseLongDepartmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseLongDepartmentName(String value) {
        this.courseLongDepartmentName = value;
    }

    /**
     * Gets the value of the courseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * Sets the value of the courseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseNumber(String value) {
        this.courseNumber = value;
    }

    /**
     * Gets the value of the courseSubID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseSubID() {
        return courseSubID;
    }

    /**
     * Sets the value of the courseSubID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseSubID(String value) {
        this.courseSubID = value;
    }

    /**
     * Gets the value of the previousCourseID property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousCourseIDType }
     *     
     */
    public PreviousCourseIDType getPreviousCourseID() {
        return previousCourseID;
    }

    /**
     * Sets the value of the previousCourseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousCourseIDType }
     *     
     */
    public void setPreviousCourseID(PreviousCourseIDType value) {
        this.previousCourseID = value;
    }

    /**
     * Gets the value of the relatedCourseID property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedCourseIDType }
     *     
     */
    public RelatedCourseIDType getRelatedCourseID() {
        return relatedCourseID;
    }

    /**
     * Sets the value of the relatedCourseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedCourseIDType }
     *     
     */
    public void setRelatedCourseID(RelatedCourseIDType value) {
        this.relatedCourseID = value;
    }

    /**
     * Gets the value of the courseShortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseShortTitle() {
        return courseShortTitle;
    }

    /**
     * Sets the value of the courseShortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseShortTitle(String value) {
        this.courseShortTitle = value;
    }

    /**
     * Gets the value of the courseLongTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseLongTitle() {
        return courseLongTitle;
    }

    /**
     * Sets the value of the courseLongTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseLongTitle(String value) {
        this.courseLongTitle = value;
    }

    /**
     * Gets the value of the courseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseDescription() {
        return courseDescription;
    }

    /**
     * Sets the value of the courseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseDescription(String value) {
        this.courseDescription = value;
    }

    /**
     * Gets the value of the courseEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCourseEffectiveDate() {
        return courseEffectiveDate;
    }

    /**
     * Sets the value of the courseEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCourseEffectiveDate(XMLGregorianCalendar value) {
        this.courseEffectiveDate = value;
    }

    /**
     * Gets the value of the courseExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseExpirationDate() {
        return courseExpirationDate;
    }

    /**
     * Sets the value of the courseExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseExpirationDate(String value) {
        this.courseExpirationDate = value;
    }

    /**
     * Gets the value of the coursePrerequisite property.
     * 
     * @return
     *     possible object is
     *     {@link CoursePrerequisiteType }
     *     
     */
    public CoursePrerequisiteType getCoursePrerequisite() {
        return coursePrerequisite;
    }

    /**
     * Sets the value of the coursePrerequisite property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoursePrerequisiteType }
     *     
     */
    public void setCoursePrerequisite(CoursePrerequisiteType value) {
        this.coursePrerequisite = value;
    }

    /**
     * Gets the value of the courseCoRequisite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courseCoRequisite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseCoRequisite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourseCorequisiteType }
     * 
     * 
     */
    public List<CourseCorequisiteType> getCourseCoRequisite() {
        if (courseCoRequisite == null) {
            courseCoRequisite = new ArrayList<CourseCorequisiteType>();
        }
        return this.courseCoRequisite;
    }

    /**
     * Gets the value of the requirement property.
     * 
     * @return
     *     possible object is
     *     {@link RAPType }
     *     
     */
    public RAPType getRequirement() {
        return requirement;
    }

    /**
     * Sets the value of the requirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link RAPType }
     *     
     */
    public void setRequirement(RAPType value) {
        this.requirement = value;
    }

    /**
     * Gets the value of the licensure property.
     * 
     * @return
     *     possible object is
     *     {@link LicensureType }
     *     
     */
    public LicensureType getLicensure() {
        return licensure;
    }

    /**
     * Sets the value of the licensure property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicensureType }
     *     
     */
    public void setLicensure(LicensureType value) {
        this.licensure = value;
    }

    /**
     * Gets the value of the languageOfInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageOfInstructionType }
     *     
     */
    public LanguageOfInstructionType getLanguageOfInstruction() {
        return languageOfInstruction;
    }

    /**
     * Sets the value of the languageOfInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageOfInstructionType }
     *     
     */
    public void setLanguageOfInstruction(LanguageOfInstructionType value) {
        this.languageOfInstruction = value;
    }

    /**
     * Gets the value of the noteMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteMessage() {
        return noteMessage;
    }

    /**
     * Sets the value of the noteMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteMessage(String value) {
        this.noteMessage = value;
    }

    /**
     * Gets the value of the userDefinedExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public UserDefinedExtensionsType getUserDefinedExtensions() {
        return userDefinedExtensions;
    }

    /**
     * Sets the value of the userDefinedExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedExtensionsType }
     *     
     */
    public void setUserDefinedExtensions(UserDefinedExtensionsType value) {
        this.userDefinedExtensions = value;
    }

}
