//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 04:54:19 PM PST 
//


package org.pesc.sector.academicrecord.v1_9;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.pesc.core.coremain.v1_14.PrerequisiteCourseConditionType;


/**
 * <p>Java class for CoursePrerequisiteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoursePrerequisiteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrerequisiteCourseIndicator" type="{urn:org:pesc:core:CoreMain:v1.14.0}PrerequisiteCourseIndicatorType"/>
 *         &lt;element name="CourseSubjectAbbreviation" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseSubjectAbbreviationType" minOccurs="0"/>
 *         &lt;element name="CourseNumber" type="{urn:org:pesc:core:CoreMain:v1.14.0}CourseNumberType" minOccurs="0"/>
 *         &lt;element name="PrerequisiteCourseCondiition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:org:pesc:core:CoreMain:v1.14.0}PrerequisiteCourseConditionType">
 *               &lt;enumeration value="Achievement"/>
 *               &lt;enumeration value="Experience"/>
 *               &lt;enumeration value="Score"/>
 *               &lt;enumeration value="Status"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoursePrerequisiteType", propOrder = {
    "prerequisiteCourseIndicator",
    "courseSubjectAbbreviation",
    "courseNumber",
    "prerequisiteCourseCondiition"
})
public class CoursePrerequisiteType {

    @XmlElement(name = "PrerequisiteCourseIndicator")
    protected boolean prerequisiteCourseIndicator;
    @XmlElement(name = "CourseSubjectAbbreviation")
    protected String courseSubjectAbbreviation;
    @XmlElement(name = "CourseNumber")
    protected String courseNumber;
    @XmlElement(name = "PrerequisiteCourseCondiition")
    protected PrerequisiteCourseConditionType prerequisiteCourseCondiition;

    /**
     * Gets the value of the prerequisiteCourseIndicator property.
     * 
     */
    public boolean isPrerequisiteCourseIndicator() {
        return prerequisiteCourseIndicator;
    }

    /**
     * Sets the value of the prerequisiteCourseIndicator property.
     * 
     */
    public void setPrerequisiteCourseIndicator(boolean value) {
        this.prerequisiteCourseIndicator = value;
    }

    /**
     * Gets the value of the courseSubjectAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseSubjectAbbreviation() {
        return courseSubjectAbbreviation;
    }

    /**
     * Sets the value of the courseSubjectAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseSubjectAbbreviation(String value) {
        this.courseSubjectAbbreviation = value;
    }

    /**
     * Gets the value of the courseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * Sets the value of the courseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseNumber(String value) {
        this.courseNumber = value;
    }

    /**
     * Gets the value of the prerequisiteCourseCondiition property.
     * 
     * @return
     *     possible object is
     *     {@link PrerequisiteCourseConditionType }
     *     
     */
    public PrerequisiteCourseConditionType getPrerequisiteCourseCondiition() {
        return prerequisiteCourseCondiition;
    }

    /**
     * Sets the value of the prerequisiteCourseCondiition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrerequisiteCourseConditionType }
     *     
     */
    public void setPrerequisiteCourseCondiition(PrerequisiteCourseConditionType value) {
        this.prerequisiteCourseCondiition = value;
    }

}
